/*
 * generator/code_gen.c — Code generation utilities.
 * Used by Forge:Visuals (and qs_build itself) to emit C/C++ source from
 * higher-level descriptions (reflection metadata, build info, PCH amalgams).
 * Also generates Zig wrappers for C libraries (C-to-Zig ABI bridge).
 */
#include "../core/include/qs_types.h"
#include "../core/include/qs_arena.h"
#include "../core/include/qs_manifest.h"
#include "../core/include/qs_fs.h"
#include <stdio.h>
#include <string.h>
#include <ctype.h>

/* Emit a C header guard from a file path */
static void emit_header_guard(FILE *f, const char *path, qs_bool_t open) {
    char guard[256]="";
    const char *base=strrchr(path,'/'); base=base?base+1:path;
    qs_size_t i=0;
    while(*base&&i<sizeof(guard)-1){
        char c=*base++;
        guard[i++]=(c=='.'||c=='-'||c==' ')?'_':((char)toupper((unsigned char)c));
    }
    guard[i]='\0';
    if(open){fprintf(f,"#ifndef %s\n#define %s\n\n",guard,guard);}
    else    {fprintf(f,"\n#endif /* %s */\n",guard);}
}

/* Generate a C-to-Zig ABI bridge header */
qs_result_t qs_gen_zig_bridge_h(qs_arena_t *a, const qs_manifest_t *m,
                                   const char *out_path) {
    FILE *f=fopen(out_path,"w"); if(!f) return QS_ERROR_IO;
    fprintf(f,"/* Auto-generated C-to-Zig ABI bridge for module %.*s */\n",
        (int)m->name.len,(const char*)m->name.ptr);
    fprintf(f,"/* Generated by qs_build — do not edit */\n\n");
    emit_header_guard(f,out_path,QS_TRUE);
    fprintf(f,"#include <stdint.h>\n#include <stddef.h>\n\n");
    fprintf(f,"#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n");
    fprintf(f,"/* Module version */\n");
    fprintf(f,"#define %.*s_VERSION \"%.*s\"\n",
        (int)m->name.len,(const char*)m->name.ptr,
        (int)m->version.len,QS_STR_IS_EMPTY(m->version)?(const qs_u8*)"0.1.0":m->version.ptr);
    fprintf(f,"\n/* TODO: add exported function declarations here */\n\n");
    fprintf(f,"#ifdef __cplusplus\n}\n#endif\n\n");
    emit_header_guard(f,out_path,QS_FALSE);
    fclose(f);
    return QS_OK;
}

/* Generate a Zig file that @cImport()s a C header */
qs_result_t qs_gen_c_import_zig(qs_arena_t *a, const char *header_path,
                                   const char *out_path) {
    FILE *f=fopen(out_path,"w"); if(!f) return QS_ERROR_IO;
    fprintf(f,"// Auto-generated C import wrapper — do not edit\n\n");
    fprintf(f,"pub const c = @cImport({\n");
    fprintf(f,"    @cInclude(\"%s\");\n",header_path);
    fprintf(f,"});\n\n");
    fprintf(f,"// Re-export common types\n");
    fprintf(f,"pub usingnamespace c;\n");
    fclose(f);
    return QS_OK;
}

/* Generate a cmake-style compile_commands.json for IDE integration */
qs_result_t qs_gen_compile_commands(qs_arena_t *a, const qs_manifest_t *m,
                                      const char *out_dir,
                                      const char *const *compile_argv,
                                      qs_size_t argc) {
    char *path=qs_arena_sprintf(a,"%s/compile_commands.json",out_dir);
    FILE *f=fopen(path,"w"); if(!f) return QS_ERROR_IO;
    fprintf(f,"[\n");
    for (qs_size_t si=0;si<m->sources.len;si++) {
        char *src=qs_arena_str_to_cstr(a,m->sources.data[si]);
        fprintf(f,"  {\n");
        fprintf(f,"    \"directory\": \"%s\",\n",out_dir);
        fprintf(f,"    \"file\": \"%s\",\n",src);
        fprintf(f,"    \"arguments\": [");
        for (qs_size_t ai=0;ai<argc;ai++) {
            fprintf(f,"\"%s\"",compile_argv[ai]);
            if(ai+1<argc) fprintf(f,",");
        }
        fprintf(f,",\"%s\"",src);
        fprintf(f,"]\n  }%s\n",si+1<m->sources.len?",":"");
    }
    fprintf(f,"]\n");
    fclose(f);
    return QS_OK;
}
