/*
 * metadata/build_info.c — Embeds build metadata into compiled artefacts.
 *
 * Generates a C source file that defines symbols readable at runtime:
 *   qs_build_commit   — git commit hash (if git is available)
 *   qs_build_date     — ISO-8601 build date/time
 *   qs_build_host     — hostname of the build machine
 *   qs_build_config   — "debug" | "release" | "profiling"
 *   qs_build_version  — version string from manifest
 *
 * Also writes a JSON sidecar file <name>.build_info.json next to the binary.
 */
#include "../core/include/qs_types.h"
#include "../core/include/qs_arena.h"
#include "../core/include/qs_manifest.h"
#include "../core/include/qs_process.h"
#include "../core/include/qs_fs.h"
#include <stdio.h>
#include <string.h>
#include <time.h>
#ifdef _WIN32
#  include <windows.h>
#endif

static char *git_commit(qs_arena_t *a) {
    char *git=qs_proc_find_in_path(a,"git");
    if (!git) return qs_arena_strdup(a,"unknown");
    const char *argv[]={"git","rev-parse","--short","HEAD",NULL};
    qs_proc_result_t pr;
    if (qs_proc_run(a,argv,NULL,5000000ULL,&pr)!=QS_OK||pr.exit_code!=0)
        return qs_arena_strdup(a,"unknown");
    /* Trim newline */
    char *s=qs_arena_strdup(a,pr.stdout_text);
    for (char *p=s;*p;p++) if (*p=='\n'||*p=='\r') { *p='\0'; break; }
    return s;
}

static char *hostname(qs_arena_t *a) {
#ifdef _WIN32
    char buf[256]="unknown";
    DWORD sz=sizeof(buf); GetComputerNameA(buf,&sz);
    return qs_arena_strdup(a,buf);
#else
    char buf[256]="unknown";
    gethostname(buf,sizeof(buf));
    return qs_arena_strdup(a,buf);
#endif
}

qs_result_t qs_build_info_generate(qs_arena_t *a, const qs_manifest_t *m,
                                     const char *out_dir, char **src_path_out) {
    /* ISO-8601 timestamp */
    time_t now=time(NULL);
    struct tm *tm=gmtime(&now);
    char ts[32];
    strftime(ts,sizeof(ts),"%Y-%m-%dT%H:%M:%SZ",tm);

    char *commit=git_commit(a);
    char *host=hostname(a);
    const char *ver=QS_STR_IS_EMPTY(m->version)?"0.1.0":(const char*)m->version.ptr;

    /* Generate C source */
    char *src=qs_arena_sprintf(a,"%s/qs_build_info.c",out_dir);
    FILE *f=fopen(src,"w"); if(!f) return QS_ERROR_IO;
    fprintf(f,"/* Auto-generated by qs_build — do not edit */\n");
    fprintf(f,"const char *qs_build_commit  = \"%s\";\n",commit);
    fprintf(f,"const char *qs_build_date    = \"%s\";\n",ts);
    fprintf(f,"const char *qs_build_host    = \"%s\";\n",host);
    fprintf(f,"const char *qs_build_version = \"%s\";\n",ver);
    fprintf(f,"const char *qs_build_name    = \"%.*s\";\n",
        (int)m->name.len,(const char*)m->name.ptr);
    fclose(f);

    /* JSON sidecar */
    char *jsn=qs_arena_sprintf(a,"%s/%.*s.build_info.json",
        out_dir,(int)m->name.len,(const char*)m->name.ptr);
    FILE *jf=fopen(jsn,"w"); if(jf) {
        fprintf(jf,"{\n");
        fprintf(jf,"  \"name\":    \"%.*s\",\n",(int)m->name.len,(const char*)m->name.ptr);
        fprintf(jf,"  \"version\": \"%s\",\n",ver);
        fprintf(jf,"  \"commit\":  \"%s\",\n",commit);
        fprintf(jf,"  \"date\":    \"%s\",\n",ts);
        fprintf(jf,"  \"host\":    \"%s\",\n",host);
        fprintf(jf,"  \"lang\":    \"%s\"\n",qs_lang_name(m->language));
        fprintf(jf,"}\n");
        fclose(jf);
    }

    if (src_path_out) *src_path_out=src;
    return QS_OK;
}
