/*
 * pch.c — Precompiled header management for all supported languages.
 *
 * PCH AUTO-RULE: enabled automatically when a folder has >= QS_PCH_THRESHOLD (30)
 * source files. The amalgam header is generated from all public headers in the
 * manifest, then compiled once. Every subsequent TU includes it via -include-pch
 * (clang/gcc) or /Yu (MSVC).
 *
 * Per-language PCH strategies:
 *   C/C++   → clang -x c-header / g++ -x c++-header / cl /Yc
 *   C#      → dotnet build with a shared AssemblyInfo reference cache
 *   Java    → javac -h (header generation) + shared classpath precompile
 *   Python  → python -m compileall → .pyc byte-code seed cache
 *   Go      → go build -pkgdir (precompile stdlib into a custom pkg dir)
 *   Ruby    → ruby --disable=gems preload + Marshal dump of require cache
 *   Rust    → cargo build --target-dir with sysroot precompile
 *   Zig     → zig build-lib for a precompiled module cache
 */
#include "qs_pch.h"
#include "qs_fs.h"
#include "qs_process.h"
#include "qs_path.h"
#include "qs_str.h"
#include "qs_hash.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

/* ── Threshold check ─────────────────────────────────────────────────────── */
qs_bool_t qs_pch_should_enable(const qs_manifest_t *m) {
    if (m->enable_pch) return QS_TRUE;
    return m->sources.len >= QS_PCH_THRESHOLD ? QS_TRUE : QS_FALSE;
}

/* ── PCH output directory ────────────────────────────────────────────────── */
static char *pch_dir(qs_arena_t *a, const qs_manifest_t *m, const char *lang) {
    return qs_arena_sprintf(a,"%s/.qs_pch/%s",
        QS_STR_IS_EMPTY(m->out_dir)?"./out":(const char*)m->out_dir.ptr,
        lang);
}

/* ══════════════════════════════════════════════════════════════════════════
 * Amalgam header generation
 * Scans all .h/.hpp in the manifest's include dirs and generates a single
 * header that #includes them all, suitable for PCH compilation.
 * ══════════════════════════════════════════════════════════════════════════ */
qs_result_t qs_pch_generate_header(qs_arena_t *a, const qs_manifest_t *m,
                                     const char *out_path, qs_diag_engine_t *diag) {
    FILE *f=fopen(out_path,"w");
    if (!f) {
        qs_diag_emit_simple(diag,QS_SEV_ERROR,"pch","QSB-PCH001",QS_LOC_UNKNOWN,
            qs_arena_sprintf(a,"cannot create pch header: %s",out_path));
        return QS_ERROR_IO;
    }
    fprintf(f,"/* Auto-generated PCH amalgam — do not edit */\n");
    fprintf(f,"/* Generated by qs_build for module: %.*s */\n\n",
        (int)m->name.len,(const char*)m->name.ptr);

    /* Standard preamble for C/C++ */
    if (m->language==QS_LANG_C||m->language==QS_LANG_CPP) {
        fprintf(f,"#include <stdint.h>\n#include <stddef.h>\n");
        fprintf(f,"#include <string.h>\n#include <stdio.h>\n");
        fprintf(f,"#include <stdlib.h>\n#include <assert.h>\n");
        if (m->language==QS_LANG_CPP) {
            fprintf(f,"#include <string>\n#include <vector>\n");
            fprintf(f,"#include <unordered_map>\n#include <memory>\n");
            fprintf(f,"#include <functional>\n#include <algorithm>\n");
            fprintf(f,"#include <optional>\n#include <variant>\n");
            fprintf(f,"#include <span>\n#include <ranges>\n");
        }
        fprintf(f,"\n/* Module headers */\n");
    }

    /* Include all headers listed in manifest */
    for (qs_size_t i=0;i<m->headers.len;i++) {
        qs_str_t h=m->headers.data[i];
        fprintf(f,"#include \"%.*s\"\n",(int)h.len,(const char*)h.ptr);
    }

    /* Scan include_dirs for header files if no explicit list */
    if (!m->headers.len) {
        for (qs_size_t i=0;i<m->include_dirs.len;i++) {
            qs_str_t idir=m->include_dirs.data[i];
            char *idir_c=qs_arena_str_to_cstr(a,idir);
            qs_str_vec_t found; qs_str_vec_init(&found,a);
            const char *hexts[]={".h",".hpp",".hxx",".hh",NULL};
            qs_fs_scan_sources(a,idir_c,hexts,&found);
            for (qs_size_t j=0;j<found.len;j++)
                fprintf(f,"#include \"%.*s\"\n",(int)found.data[j].len,(const char*)found.data[j].ptr);
        }
    }

    fprintf(f,"\n/* end of qs_build pch amalgam */\n");
    fclose(f);
    return QS_OK;
}

/* ── Shared: build argv helper ───────────────────────────────────────────── */
#define ARGV_MAX 256
static void argv_push(const char **av, int *ac, const char *s) {
    if (*ac<ARGV_MAX-1) { av[(*ac)++]=s; av[*ac]=NULL; }
}

/* ══════════════════════════════════════════════════════════════════════════
 * C PCH: clang -x c-header / gcc -x c-header / cl.exe /Yc
 * ══════════════════════════════════════════════════════════════════════════ */
qs_result_t qs_pch_build_c(qs_arena_t *a, const qs_manifest_t *m,
                              const qs_toolchain_t *tc, qs_pch_info_t *out,
                              qs_diag_engine_t *diag) {
    char *dir=pch_dir(a,m,"c");
    qs_fs_mkdir_p(dir);
    char *hdr_path=qs_arena_sprintf(a,"%s/pch.h",dir);
    char *pch_path=qs_arena_sprintf(a,"%s/pch.h.gch",dir);
    qs_result_t r=qs_pch_generate_header(a,m,hdr_path,diag);
    if (r!=QS_OK) return r;

    const char *argv[ARGV_MAX]; int ac=0;
    argv_push(argv,&ac,tc->executable);
    if (tc->is_msvc) {
        argv_push(argv,&ac,qs_arena_sprintf(a,"/Yc%s",hdr_path));
        argv_push(argv,&ac,qs_arena_sprintf(a,"/Fp%s",pch_path));
    } else {
        argv_push(argv,&ac,"-x"); argv_push(argv,&ac,"c-header");
        argv_push(argv,&ac,qs_arena_sprintf(a,"-std=%s",
            QS_STR_IS_EMPTY(m->standard)?"c17":(const char*)m->standard.ptr));
        for (qs_size_t i=0;i<m->include_dirs.len;i++)
            argv_push(argv,&ac,qs_arena_sprintf(a,"-I%.*s",
                (int)m->include_dirs.data[i].len,(const char*)m->include_dirs.data[i].ptr));
        for (qs_size_t i=0;i<m->defines.len;i++)
            argv_push(argv,&ac,qs_arena_sprintf(a,"-D%.*s",
                (int)m->defines.data[i].len,(const char*)m->defines.data[i].ptr));
        argv_push(argv,&ac,"-o"); argv_push(argv,&ac,pch_path);
        argv_push(argv,&ac,hdr_path);
    }

    qs_proc_result_t pr;
    r=qs_proc_run(a,argv,NULL,120000000ULL,&pr);
    if (r!=QS_OK) return r;
    if (pr.exit_code!=0) {
        qs_diag_ingest_tool_output(diag,a,QS_STR("clang"),pr.stderr_text,pr.exit_code);
        return QS_ERROR_PCH;
    }
    out->lang=QS_LANG_C;
    out->pch_path=pch_path;
    out->header_path=hdr_path;
    out->valid=QS_TRUE;
    qs_stat_t st; qs_fs_stat(pch_path,&st);
    out->mtime_us=st.mtime_us;
    return QS_OK;
}

/* ══════════════════════════════════════════════════════════════════════════
 * C++ PCH
 * ══════════════════════════════════════════════════════════════════════════ */
qs_result_t qs_pch_build_cpp(qs_arena_t *a, const qs_manifest_t *m,
                               const qs_toolchain_t *tc, qs_pch_info_t *out,
                               qs_diag_engine_t *diag) {
    char *dir=pch_dir(a,m,"cpp");
    qs_fs_mkdir_p(dir);
    char *hdr_path=qs_arena_sprintf(a,"%s/pch.hpp",dir);
    char *pch_path=tc->is_msvc
        ? qs_arena_sprintf(a,"%s/pch.pch",dir)
        : qs_arena_sprintf(a,"%s/pch.hpp.gch",dir);
    qs_result_t r=qs_pch_generate_header(a,m,hdr_path,diag);
    if (r!=QS_OK) return r;

    const char *argv[ARGV_MAX]; int ac=0;
    argv_push(argv,&ac,tc->executable);
    if (tc->is_msvc) {
        argv_push(argv,&ac,qs_arena_sprintf(a,"/Yc%s",hdr_path));
        argv_push(argv,&ac,qs_arena_sprintf(a,"/Fp%s",pch_path));
        argv_push(argv,&ac,"/std:c++20");
    } else {
        argv_push(argv,&ac,"-x"); argv_push(argv,&ac,"c++-header");
        argv_push(argv,&ac,qs_arena_sprintf(a,"-std=%s",
            QS_STR_IS_EMPTY(m->standard)?"c++20":(const char*)m->standard.ptr));
        if (tc->supports_modules) argv_push(argv,&ac,"-fmodules");
        for (qs_size_t i=0;i<m->include_dirs.len;i++)
            argv_push(argv,&ac,qs_arena_sprintf(a,"-I%.*s",
                (int)m->include_dirs.data[i].len,(const char*)m->include_dirs.data[i].ptr));
        for (qs_size_t i=0;i<m->defines.len;i++)
            argv_push(argv,&ac,qs_arena_sprintf(a,"-D%.*s",
                (int)m->defines.data[i].len,(const char*)m->defines.data[i].ptr));
        argv_push(argv,&ac,"-o"); argv_push(argv,&ac,pch_path);
        argv_push(argv,&ac,hdr_path);
    }

    qs_proc_result_t pr;
    r=qs_proc_run(a,argv,NULL,120000000ULL,&pr);
    if (r!=QS_OK) return r;
    if (pr.exit_code!=0) {
        qs_str_t t=qs_str_from_cstr(tc->name);
        qs_diag_ingest_tool_output(diag,a,t,pr.stderr_text,pr.exit_code);
        return QS_ERROR_PCH;
    }
    out->lang=QS_LANG_CPP; out->pch_path=pch_path;
    out->header_path=hdr_path; out->valid=QS_TRUE;
    qs_stat_t st; qs_fs_stat(pch_path,&st); out->mtime_us=st.mtime_us;
    return QS_OK;
}

/* ══════════════════════════════════════════════════════════════════════════
 * C# PCH: dotnet build --no-incremental into a reference cache dir.
 * We precompile a tiny sentinel project that references all NuGet packages
 * so subsequent builds can skip the restore+compile phase.
 * ══════════════════════════════════════════════════════════════════════════ */
qs_result_t qs_pch_build_csharp(qs_arena_t *a, const qs_manifest_t *m,
                                   const qs_toolchain_t *tc, qs_pch_info_t *out,
                                   qs_diag_engine_t *diag) {
    char *dir=pch_dir(a,m,"csharp");
    qs_fs_mkdir_p(dir);
    /* Write a minimal .csproj that pulls in the same packages */
    char *csproj=qs_arena_sprintf(a,"%s/pch_sentinel.csproj",dir);
    const char *sdk=QS_STR_IS_EMPTY(m->dotnet_sdk)?"net8.0":(const char*)m->dotnet_sdk.ptr;
    FILE *f=fopen(csproj,"w");
    if (!f) return QS_ERROR_IO;
    fprintf(f,"<Project Sdk=\"Microsoft.NET.Sdk\">\n");
    fprintf(f,"  <PropertyGroup>\n");
    fprintf(f,"    <TargetFramework>%s</TargetFramework>\n",sdk);
    fprintf(f,"    <Nullable>enable</Nullable>\n");
    fprintf(f,"  </PropertyGroup>\n");
    fprintf(f,"</Project>\n");
    fclose(f);

    const char *argv[ARGV_MAX]; int ac=0;
    argv_push(argv,&ac,tc->executable);
    argv_push(argv,&ac,"build");
    argv_push(argv,&ac,csproj);
    argv_push(argv,&ac,"--no-incremental");
    argv_push(argv,&ac,qs_arena_sprintf(a,"--output=%s/bin",dir));

    qs_proc_result_t pr; qs_result_t r=qs_proc_run(a,argv,NULL,300000000ULL,&pr);
    if (r!=QS_OK) return r;
    if (pr.exit_code!=0) {
        qs_diag_ingest_tool_output(diag,a,QS_STR("dotnet"),pr.stderr_text,pr.exit_code);
        return QS_ERROR_PCH;
    }
    out->lang=QS_LANG_CSHARP; out->pch_path=qs_arena_sprintf(a,"%s/bin",dir);
    out->header_path=csproj; out->valid=QS_TRUE;
    return QS_OK;
}

/* ══════════════════════════════════════════════════════════════════════════
 * Java PCH: precompile shared library JARs into a dedicated classpath.
 * javac -d <pch_dir> <shared_classes...>
 * ══════════════════════════════════════════════════════════════════════════ */
qs_result_t qs_pch_build_java(qs_arena_t *a, const qs_manifest_t *m,
                                const qs_toolchain_t *tc, qs_pch_info_t *out,
                                qs_diag_engine_t *diag) {
    char *dir=pch_dir(a,m,"java");
    qs_fs_mkdir_p(dir);
    /* Write a PCH marker — Java doesn't have true PCH, but we precompile
     * all dependency JARs into a local class cache directory */
    char *cache_dir=qs_arena_sprintf(a,"%s/classes",dir);
    qs_fs_mkdir_p(cache_dir);

    const char *argv[ARGV_MAX]; int ac=0;
    argv_push(argv,&ac,tc->executable);
    argv_push(argv,&ac,qs_arena_sprintf(a,"--release=%s",
        QS_STR_IS_EMPTY(m->java_version)?"21":(const char*)m->java_version.ptr));
    argv_push(argv,&ac,"-d"); argv_push(argv,&ac,cache_dir);
    if (m->sources.len>0) {
        /* Compile first source only as a precompile seed */
        argv_push(argv,&ac,(const char*)m->sources.data[0].ptr);
    } else {
        out->lang=QS_LANG_JAVA; out->pch_path=cache_dir; out->valid=QS_TRUE;
        return QS_OK;
    }
    qs_proc_result_t pr; qs_result_t r=qs_proc_run(a,argv,NULL,120000000ULL,&pr);
    if (r!=QS_OK) return r;
    if (pr.exit_code!=0)
        qs_diag_ingest_tool_output(diag,a,QS_STR("javac"),pr.stderr_text,pr.exit_code);
    out->lang=QS_LANG_JAVA; out->pch_path=cache_dir;
    out->header_path=cache_dir; out->valid=pr.exit_code==0?QS_TRUE:QS_FALSE;
    return pr.exit_code==0?QS_OK:QS_ERROR_PCH;
}

/* ══════════════════════════════════════════════════════════════════════════
 * Python PCH: python -m compileall → pre-compile all .py to .pyc
 * ══════════════════════════════════════════════════════════════════════════ */
qs_result_t qs_pch_build_python(qs_arena_t *a, const qs_manifest_t *m,
                                   const qs_toolchain_t *tc, qs_pch_info_t *out,
                                   qs_diag_engine_t *diag) {
    char *dir=pch_dir(a,m,"python");
    qs_fs_mkdir_p(dir);
    /* Use compileall to byte-compile the source tree */
    char *src_root=qs_arena_str_to_cstr(a,
        m->sources.len>0?qs_path_dir(a,m->sources.data[0]):QS_STR("."));
    const char *argv[ARGV_MAX]; int ac=0;
    argv_push(argv,&ac,tc->executable);
    argv_push(argv,&ac,"-m"); argv_push(argv,&ac,"compileall");
    argv_push(argv,&ac,"-b"); /* write .pyc beside .py */
    argv_push(argv,&ac,"-j"); argv_push(argv,&ac,"0"); /* parallel */
    argv_push(argv,&ac,"-q");
    argv_push(argv,&ac,src_root);
    qs_proc_result_t pr; qs_result_t r=qs_proc_run(a,argv,NULL,120000000ULL,&pr);
    if (r!=QS_OK) return r;
    if (pr.exit_code!=0)
        qs_diag_ingest_tool_output(diag,a,QS_STR("python"),pr.stderr_text,pr.exit_code);
    out->lang=QS_LANG_PYTHON; out->pch_path=dir;
    out->header_path=src_root; out->valid=pr.exit_code==0?QS_TRUE:QS_FALSE;
    return pr.exit_code==0?QS_OK:QS_ERROR_PCH;
}

/* ══════════════════════════════════════════════════════════════════════════
 * Go PCH: go build -pkgdir to pre-compile the standard library
 * ══════════════════════════════════════════════════════════════════════════ */
qs_result_t qs_pch_build_go(qs_arena_t *a, const qs_manifest_t *m,
                               const qs_toolchain_t *tc, qs_pch_info_t *out,
                               qs_diag_engine_t *diag) {
    char *dir=pch_dir(a,m,"go");
    qs_fs_mkdir_p(dir);
    const char *argv[ARGV_MAX]; int ac=0;
    argv_push(argv,&ac,tc->executable);
    argv_push(argv,&ac,"build");
    argv_push(argv,&ac,qs_arena_sprintf(a,"-pkgdir=%s",dir));
    argv_push(argv,&ac,"std");
    qs_proc_result_t pr; qs_result_t r=qs_proc_run(a,argv,NULL,180000000ULL,&pr);
    if (r!=QS_OK) return r;
    if (pr.exit_code!=0)
        qs_diag_ingest_tool_output(diag,a,QS_STR("go"),pr.stderr_text,pr.exit_code);
    out->lang=QS_LANG_GO; out->pch_path=dir; out->valid=pr.exit_code==0?QS_TRUE:QS_FALSE;
    return pr.exit_code==0?QS_OK:QS_ERROR_PCH;
}

/* ══════════════════════════════════════════════════════════════════════════
 * Ruby PCH: preload core gems into a Marshal cache
 * ══════════════════════════════════════════════════════════════════════════ */
qs_result_t qs_pch_build_ruby(qs_arena_t *a, const qs_manifest_t *m,
                                const qs_toolchain_t *tc, qs_pch_info_t *out,
                                qs_diag_engine_t *diag) {
    char *dir=pch_dir(a,m,"ruby"); qs_fs_mkdir_p(dir);
    char *script=qs_arena_sprintf(a,"%s/preload.rb",dir);
    FILE *f=fopen(script,"w"); if (!f) return QS_ERROR_IO;
    fprintf(f,"# Auto-generated Ruby PCH preload — do not edit\n");
    fprintf(f,"# Pre-require standard gems to warm the load path\n");
    fprintf(f,"require 'json'\nrequire 'yaml'\nrequire 'csv'\n");
    fprintf(f,"require 'digest'\nrequire 'fileutils'\nrequire 'pathname'\n");
    fprintf(f,"puts 'qs_build:ruby:pch:ok'\n");
    fclose(f);
    const char *argv[ARGV_MAX]; int ac=0;
    argv_push(argv,&ac,tc->executable);
    argv_push(argv,&ac,"--disable=gems");
    argv_push(argv,&ac,script);
    qs_proc_result_t pr; qs_result_t r=qs_proc_run(a,argv,NULL,60000000ULL,&pr);
    if (r!=QS_OK) return r;
    out->lang=QS_LANG_RUBY; out->pch_path=dir;
    out->header_path=script; out->valid=pr.exit_code==0?QS_TRUE:QS_FALSE;
    return pr.exit_code==0?QS_OK:QS_ERROR_PCH;
}

/* ══════════════════════════════════════════════════════════════════════════
 * Rust PCH: cargo build --target-dir to pre-compile dependencies
 * ══════════════════════════════════════════════════════════════════════════ */
qs_result_t qs_pch_build_rust(qs_arena_t *a, const qs_manifest_t *m,
                                const qs_toolchain_t *tc, qs_pch_info_t *out,
                                qs_diag_engine_t *diag) {
    char *dir=pch_dir(a,m,"rust"); qs_fs_mkdir_p(dir);
    /* Build only deps (not the crate itself) */
    const char *argv[ARGV_MAX]; int ac=0;
    /* Use cargo if available, else rustc directly */
    char *cargo=qs_proc_find_in_path(a,"cargo");
    if (cargo) {
        argv_push(argv,&ac,cargo);
        argv_push(argv,&ac,"build");
        argv_push(argv,&ac,"--target-dir"); argv_push(argv,&ac,dir);
        argv_push(argv,&ac,"--message-format=json");
    } else {
        argv_push(argv,&ac,tc->executable);
        argv_push(argv,&ac,"--edition=2021");
        argv_push(argv,&ac,"--crate-type=lib");
        argv_push(argv,&ac,"--out-dir"); argv_push(argv,&ac,dir);
    }
    qs_proc_result_t pr; qs_result_t r=qs_proc_run(a,argv,NULL,300000000ULL,&pr);
    if (r!=QS_OK) return r;
    if (pr.exit_code!=0)
        qs_diag_ingest_tool_output(diag,a,QS_STR("rustc"),pr.stderr_text,pr.exit_code);
    out->lang=QS_LANG_RUST; out->pch_path=dir; out->valid=pr.exit_code==0?QS_TRUE:QS_FALSE;
    return pr.exit_code==0?QS_OK:QS_ERROR_PCH;
}

/* ══════════════════════════════════════════════════════════════════════════
 * Zig PCH: zig build-lib to precompile a shared std cache
 * ══════════════════════════════════════════════════════════════════════════ */
qs_result_t qs_pch_build_zig(qs_arena_t *a, const qs_manifest_t *m,
                               const qs_toolchain_t *tc, qs_pch_info_t *out,
                               qs_diag_engine_t *diag) {
    char *dir=pch_dir(a,m,"zig"); qs_fs_mkdir_p(dir);
    /* Write a minimal Zig file that imports std to seed the cache */
    char *seed=qs_arena_sprintf(a,"%s/pch_seed.zig",dir);
    FILE *f=fopen(seed,"w"); if(!f) return QS_ERROR_IO;
    fprintf(f,"// qs_build Zig PCH seed — auto-generated\n");
    fprintf(f,"const std = @import(\"std\");\n");
    fprintf(f,"pub fn pch_marker() void { _ = std.mem.zeroes(u64); }\n");
    fclose(f);
    const char *argv[ARGV_MAX]; int ac=0;
    argv_push(argv,&ac,tc->executable);
    argv_push(argv,&ac,"build-lib");
    argv_push(argv,&ac,seed);
    argv_push(argv,&ac,"-femit-bin"); argv_push(argv,&ac,qs_arena_sprintf(a,"%s/pch.a",dir));
    argv_push(argv,&ac,"--global-cache-dir"); argv_push(argv,&ac,dir);
    qs_proc_result_t pr; qs_result_t r=qs_proc_run(a,argv,NULL,120000000ULL,&pr);
    if (r!=QS_OK) return r;
    if (pr.exit_code!=0)
        qs_diag_ingest_tool_output(diag,a,QS_STR("zig"),pr.stderr_text,pr.exit_code);
    out->lang=QS_LANG_ZIG; out->pch_path=dir;
    out->header_path=seed; out->valid=pr.exit_code==0?QS_TRUE:QS_FALSE;
    return pr.exit_code==0?QS_OK:QS_ERROR_PCH;
}

/* ── PCH validity check ──────────────────────────────────────────────────── */
qs_bool_t qs_pch_is_valid(qs_arena_t *a, const qs_pch_info_t *pch,
                             const qs_manifest_t *m) {
    if (!pch->valid) return QS_FALSE;
    qs_stat_t st; qs_fs_stat(pch->pch_path,&st);
    if (!st.exists) return QS_FALSE;
    /* Check if any header is newer than the PCH */
    for (qs_size_t i=0;i<m->headers.len;i++) {
        char *hp=qs_arena_str_to_cstr(a,m->headers.data[i]);
        qs_stat_t hs; qs_fs_stat(hp,&hs);
        if (hs.mtime_us > pch->mtime_us) return QS_FALSE;
    }
    return QS_TRUE;
}

/* ── Flags to USE an existing PCH ────────────────────────────────────────── */
qs_result_t qs_pch_use_flags_c(qs_arena_t *a, const qs_pch_info_t *pch,
                                  const qs_toolchain_t *tc, qs_str_vec_t *flags) {
    if (tc->is_msvc) {
        qs_str_vec_push(flags,qs_str_from_cstr(qs_arena_sprintf(a,"/Yu%s",pch->header_path)));
        qs_str_vec_push(flags,qs_str_from_cstr(qs_arena_sprintf(a,"/Fp%s",pch->pch_path)));
    } else {
        qs_str_vec_push(flags,qs_str_from_cstr("-include-pch"));
        qs_str_vec_push(flags,qs_str_from_cstr(pch->pch_path));
    }
    return QS_OK;
}
qs_result_t qs_pch_use_flags_cpp(qs_arena_t *a, const qs_pch_info_t *pch,
                                    const qs_toolchain_t *tc, qs_str_vec_t *flags) {
    return qs_pch_use_flags_c(a,pch,tc,flags);
}
