/*
 * compiler/zig_driver.c — Zig build driver.
 * Invokes `zig build-exe`, `zig build-lib`, `zig build-obj`, or `zig build`
 * (when build.zig present). Zig is self-hosted; no separate linker invocation.
 * Also handles `zig cc` as a drop-in C compiler for C sources that want
 * Zig's clang frontend + caching.
 */
#include "../core/include/qs_types.h"
#include "../core/include/qs_arena.h"
#include "../core/include/qs_manifest.h"
#include "../core/include/qs_toolchain.h"
#include "../core/include/qs_diag.h"
#include "../core/include/qs_process.h"
#include "../core/include/qs_fs.h"
#include "../core/include/qs_path.h"
#include <string.h>
#include <stdio.h>

#define ARGV_MAX 512
static int zig_ac; static const char *zig_av[ARGV_MAX];
#define PUSH(s)      do{if(zig_ac<ARGV_MAX-1){zig_av[zig_ac++]=(s);zig_av[zig_ac]=NULL;}}while(0)
#define PUSHF(f,...) PUSH(qs_arena_sprintf(a,f,__VA_ARGS__))

/* Generate build.zig when the project doesn't have one */
static char *gen_build_zig(qs_arena_t *a, const qs_manifest_t *m, const char *src_dir) {
    char *path = qs_arena_sprintf(a,"%s/build.zig",src_dir);
    if (qs_fs_exists(path)) return path;
    FILE *f = fopen(path,"w"); if(!f) return NULL;
    fprintf(f,"// Auto-generated by qs_build — safe to customise\n");
    fprintf(f,"const std = @import(\"std\");\n\n");
    fprintf(f,"pub fn build(b: *std.Build) void {\n");
    fprintf(f,"    const target   = b.standardTargetOptions(.{});\n");
    fprintf(f,"    const optimize = b.standardOptimizeOption(.{});\n\n");

    const char *artifact_fn;
    switch (m->output_type) {
        case QS_OUT_LIB:    artifact_fn = "addStaticLibrary"; break;
        case QS_OUT_DLL:    artifact_fn = "addSharedLibrary"; break;
        case QS_OUT_OBJECT: artifact_fn = "addObject";        break;
        default:            artifact_fn = "addExecutable";    break;
    }
    fprintf(f,"    const art = b.%s(.{\n",artifact_fn);
    fprintf(f,"        .name     = \"%.*s\",\n",(int)m->name.len,(const char*)m->name.ptr);
    /* Use first .zig source as root, or generate a stub */
    const char *root = "src/main.zig";
    for (qs_size_t i=0;i<m->sources.len;i++) {
        qs_str_t ext=qs_path_ext(m->sources.data[i]);
        if (qs_str_eq_cstr(ext,".zig")) { root=(const char*)m->sources.data[i].ptr; break; }
    }
    fprintf(f,"        .root_source_file = b.path(\"%s\"),\n",root);
    fprintf(f,"        .target   = target,\n");
    fprintf(f,"        .optimize = optimize,\n");
    fprintf(f,"    });\n\n");
    /* Add C source files */
    for (qs_size_t i=0;i<m->sources.len;i++) {
        qs_str_t ext=qs_path_ext(m->sources.data[i]);
        if (qs_str_eq_cstr(ext,".c")||qs_str_eq_cstr(ext,".cpp")) {
            fprintf(f,"    art.addCSourceFile(.{ .file = b.path(\"%.*s\"), .flags = &.{} });\n",
                (int)m->sources.data[i].len,(const char*)m->sources.data[i].ptr);
        }
    }
    for (qs_size_t i=0;i<m->include_dirs.len;i++)
        fprintf(f,"    art.addIncludePath(b.path(\"%.*s\"));\n",
            (int)m->include_dirs.data[i].len,(const char*)m->include_dirs.data[i].ptr);
    fprintf(f,"\n    b.installArtifact(art);\n}\n");
    fclose(f);
    return path;
}

qs_result_t qs_zig_build(qs_arena_t *a, const qs_manifest_t *m,
                           const qs_toolchain_t *tc,
                           const char *src_dir, const char *out_dir,
                           const char *target_triple,
                           qs_diag_engine_t *diag,
                           qs_bool_t verbose, qs_bool_t dry_run,
                           char **output_path_out) {
    qs_fs_mkdir_p(out_dir);
    char *bzig = qs_arena_sprintf(a,"%s/build.zig",src_dir);

    /* Prefer zig build if build.zig exists or we generate one */
    gen_build_zig(a,m,src_dir);
    zig_ac=0;
    PUSH(tc->executable); PUSH("build");
    PUSHF("--prefix=%s",out_dir);
    PUSH("-Doptimize=ReleaseFast");
    if (target_triple && *target_triple) PUSHF("-Dtarget=%s",target_triple);
    PUSHF("--cache-dir=%s/.zig-cache",out_dir);
    PUSHF("--global-cache-dir=%s/.zig-global-cache",out_dir);

    if (verbose) qs_proc_print_argv(zig_av);
    if (dry_run) return QS_OK;

    /* Run from src_dir so build.zig can find relative paths */
    qs_proc_result_t pr;
    qs_result_t r=qs_proc_run(a,zig_av,NULL,600000000ULL,&pr);
    if (r!=QS_OK) return r;

    const char *err=pr.stderr_text[0]?pr.stderr_text:pr.stdout_text;
    qs_diag_ingest_tool_output(diag,a,QS_STR("zig"),err,pr.exit_code);

    if (output_path_out)
        *output_path_out=qs_arena_sprintf(a,"%s/bin/%.*s",
            out_dir,(int)m->name.len,(const char*)m->name.ptr);
    return pr.exit_code==0?QS_OK:QS_ERROR_COMPILE;
}

/* Compile a single C file using zig cc (uses Zig's clang + cache) */
qs_result_t qs_zigcc_compile_file(qs_arena_t *a, const qs_manifest_t *m,
                                    const qs_toolchain_t *tc,
                                    const char *src, const char *obj,
                                    qs_diag_engine_t *diag,
                                    qs_bool_t verbose, qs_bool_t dry_run) {
    zig_ac=0;
    PUSH(tc->executable); PUSH("cc");
    PUSHF("-std=%s",QS_STR_IS_EMPTY(m->standard)?"c17":(const char*)m->standard.ptr);
    PUSH("-Wall"); PUSH("-Wextra");
    if (m->enable_lto) PUSH("-flto");
    for (qs_size_t i=0;i<m->include_dirs.len;i++)
        PUSHF("-I%.*s",(int)m->include_dirs.data[i].len,(const char*)m->include_dirs.data[i].ptr);
    for (qs_size_t i=0;i<m->defines.len;i++)
        PUSHF("-D%.*s",(int)m->defines.data[i].len,(const char*)m->defines.data[i].ptr);
    PUSH("-c"); PUSH("-o"); PUSH(obj); PUSH(src);
    if (verbose) qs_proc_print_argv(zig_av);
    if (dry_run) return QS_OK;
    qs_proc_result_t pr;
    qs_result_t r=qs_proc_run(a,zig_av,NULL,120000000ULL,&pr);
    if (r!=QS_OK) return r;
    qs_diag_ingest_tool_output(diag,a,QS_STR("zig"),pr.stderr_text,pr.exit_code);
    return pr.exit_code==0?QS_OK:QS_ERROR_COMPILE;
}
