/*
 * errors/errors.c — Complete error catalogue for qs_build.
 *
 * One qs_error_entry_t row per QSB-XXXnnn code.  The table is terminated
 * by a sentinel entry (code == NULL).  qs_error_lookup() does a linear
 * scan — the catalogue is only ~200 entries so a hash table is unnecessary.
 *
 * Public API:
 *   qs_error_lookup()       find entry by code string
 *   qs_error_emit()         look up + emit via diag engine (convenience)
 *   qs_error_count()        total number of registered codes
 *   qs_error_catalog_ptr()  raw array pointer for iteration
 */
#include "../core/include/qs_errors.h"
#include "../core/include/qs_arena.h"
#include "../core/include/qs_str.h"
#include <string.h>
#include <stdio.h>

/* Base documentation URL prefix — appended with the lowercase code */
#define DOC_BASE "https://docs.qs-build.dev/errors/"

/* Shorthand to keep the table readable */
#define E  QS_SEV_ERROR
#define W  QS_SEV_WARNING
#define N  QS_SEV_NOTE
#define F  QS_SEV_FATAL

static const qs_error_entry_t CATALOG[] = {

/* ── QSB-ARG  CLI argument / option errors ──────────────────────────────── */
{ QSB_ARG001, E, "unknown-flag",
  "Run 'qs_build --help' to see all supported flags.",
  DOC_BASE "qsb-arg001" },
{ QSB_ARG002, E, "flag-requires-value",
  "Provide a value immediately after the flag, e.g. '--jobs 4'.",
  DOC_BASE "qsb-arg002" },
{ QSB_ARG003, E, "invalid-flag-value",
  "Check the allowed values in 'qs_build --help'.",
  DOC_BASE "qsb-arg003" },
{ QSB_ARG004, E, "conflicting-flags",
  "Remove one of the conflicting flags.",
  DOC_BASE "qsb-arg004" },
{ QSB_ARG005, E, "jobs-out-of-range",
  "--jobs must be >= 1; omit it to use the CPU core count.",
  DOC_BASE "qsb-arg005" },
{ QSB_ARG006, E, "error-limit-out-of-range",
  "--error-limit must be >= 0 (0 = unlimited).",
  DOC_BASE "qsb-arg006" },
{ QSB_ARG007, E, "chunk-size-out-of-range",
  "--chunk-size must be >= 1.",
  DOC_BASE "qsb-arg007" },
{ QSB_ARG008, E, "manifest-path-missing",
  "Specify the path to a build.qs file or run from its directory.",
  DOC_BASE "qsb-arg008" },
{ QSB_ARG009, E, "unknown-subcommand",
  "Known sub-commands: new, migrate, verify. Run --help for details.",
  DOC_BASE "qsb-arg009" },
{ QSB_ARG010, E, "malformed-target-triple",
  "Use the form arch-vendor-os-abi, e.g. aarch64-unknown-linux-gnu.",
  DOC_BASE "qsb-arg010" },
{ QSB_ARG011, E, "invalid-profile",
  "Valid profiles: debug, release, relwithdebinfo, profiling.",
  DOC_BASE "qsb-arg011" },
{ QSB_ARG012, E, "invalid-output-type",
  "Valid types: exe, dll, lib, app, qpkg, wheel, jar, gem, gobin.",
  DOC_BASE "qsb-arg012" },
{ QSB_ARG013, E, "too-many-arguments",
  "Only one positional argument (manifest path) is accepted.",
  DOC_BASE "qsb-arg013" },
{ QSB_ARG014, W, "duplicate-flag",
  "The second occurrence of this flag overrides the first.",
  DOC_BASE "qsb-arg014" },
{ QSB_ARG015, E, "out-dir-is-file",
  "The --out path already exists as a regular file; choose a different path.",
  DOC_BASE "qsb-arg015" },

/* ── QSB-AST  AST / parser internal errors ──────────────────────────────── */
{ QSB_AST001, E, "unexpected-token",
  "Check the build.qs syntax around the indicated position.",
  DOC_BASE "qsb-ast001" },
{ QSB_AST002, E, "unexpected-eof",
  "The file appears to be truncated or an opening brace is unclosed.",
  DOC_BASE "qsb-ast002" },
{ QSB_AST003, E, "unterminated-string",
  "Add a closing '\"' to the string literal.",
  DOC_BASE "qsb-ast003" },
{ QSB_AST004, E, "unclosed-list",
  "Add a closing ']' to the list.",
  DOC_BASE "qsb-ast004" },
{ QSB_AST005, E, "unclosed-block",
  "Add a closing '}' to the module block.",
  DOC_BASE "qsb-ast005" },
{ QSB_AST006, E, "expected-equals",
  "Key-value pairs require '=' between the key and value.",
  DOC_BASE "qsb-ast006" },
{ QSB_AST007, E, "expected-semicolon",
  "Add ';' at the end of the statement.",
  DOC_BASE "qsb-ast007" },
{ QSB_AST008, W, "duplicate-key",
  "The second assignment overwrites the first; remove the duplicate.",
  DOC_BASE "qsb-ast008" },

/* ── QSB-CHK  Unity-chunker errors ─────────────────────────────────────── */
{ QSB_CHK001, E, "chunk-write-failed",
  "Check available disk space and permissions in the output directory.",
  DOC_BASE "qsb-chk001" },
{ QSB_CHK002, E, "chunk-source-unreadable",
  "Ensure the source file exists and is readable.",
  DOC_BASE "qsb-chk002" },
{ QSB_CHK003, E, "chunk-plan-empty",
  "No source files were available to chunk; add sources to the manifest.",
  DOC_BASE "qsb-chk003" },
{ QSB_CHK004, E, "chunk-size-zero",
  "Set chunk_size to a value >= 1 in the manifest or use --chunk-size.",
  DOC_BASE "qsb-chk004" },
{ QSB_CHK005, E, "chunk-file-create-failed",
  "Check write permissions on the output directory.",
  DOC_BASE "qsb-chk005" },
{ QSB_CHK006, W, "no-unity-not-honoured",
  "Verify the NO_UNITY pragma is at file scope with the correct spelling.",
  DOC_BASE "qsb-chk006" },
{ QSB_CHK007, E, "header-scan-io-error",
  "Ensure all headers listed in the manifest exist on disk.",
  DOC_BASE "qsb-chk007" },
{ QSB_CHK010, E, "chunk-outdir-create-failed",
  "Check permissions on the parent of the output directory.",
  DOC_BASE "qsb-chk010" },

/* ── QSB-CFG  Config errors ─────────────────────────────────────────────── */
{ QSB_CFG001, E, "qsbuildrc-parse-error",
  "Check the syntax of your .qsbuildrc file (KEY = value format).",
  DOC_BASE "qsb-cfg001" },
{ QSB_CFG002, W, "qsbuildrc-unknown-key",
  "Remove the unrecognised key or check for a typo.",
  DOC_BASE "qsb-cfg002" },
{ QSB_CFG003, E, "qsbuildrc-wrong-type",
  "Consult the .qsbuildrc reference for expected value types.",
  DOC_BASE "qsb-cfg003" },
{ QSB_CFG004, W, "env-var-malformed",
  "Unset the environment variable or correct its value.",
  DOC_BASE "qsb-cfg004" },
{ QSB_CFG005, E, "config-file-open-failed",
  "Check that the .qsbuildrc file exists and is readable.",
  DOC_BASE "qsb-cfg005" },
{ QSB_CFG006, W, "config-conflict",
  "CLI flags take highest precedence, then env vars, then .qsbuildrc.",
  DOC_BASE "qsb-cfg006" },
{ QSB_CFG007, E, "config-value-out-of-range",
  "Check the allowed range in the .qsbuildrc reference.",
  DOC_BASE "qsb-cfg007" },

/* ── QSB-CMP  Generic compile-phase errors ──────────────────────────────── */
{ QSB_CMP001, E, "compiler-spawn-failed",
  "Ensure the compiler is installed and the executable is on PATH.",
  DOC_BASE "qsb-cmp001" },
{ QSB_CMP002, E, "compiler-nonzero-exit",
  "Examine the errors above; fix the source code or compiler flags.",
  DOC_BASE "qsb-cmp002" },
{ QSB_CMP003, E, "compilation-timeout",
  "Increase --timeout or reduce the number of parallel --jobs.",
  DOC_BASE "qsb-cmp003" },
{ QSB_CMP004, E, "no-sources",
  "Add at least one source file to the 'sources' list in build.qs.",
  DOC_BASE "qsb-cmp004" },
{ QSB_CMP005, E, "output-not-produced",
  "Check that the compile step succeeded and the output path is writable.",
  DOC_BASE "qsb-cmp005" },
{ QSB_CMP006, W, "stderr-truncated",
  "Increase QS_PROC_STDERR_MAX or reduce the verbosity of compiler output.",
  DOC_BASE "qsb-cmp006" },
{ QSB_CMP007, E, "command-too-long",
  "Reduce the number of include paths or use response files.",
  DOC_BASE "qsb-cmp007" },
{ QSB_CMP008, E, "incompatible-standard",
  "Set a standard version supported by the installed compiler.",
  DOC_BASE "qsb-cmp008" },
{ QSB_CMP009, W, "invalid-define-char",
  "Defines may only contain [A-Za-z0-9_=] characters.",
  DOC_BASE "qsb-cmp009" },
{ QSB_CMP010, W, "invalid-include-path-char",
  "Include paths must not contain shell-special characters.",
  DOC_BASE "qsb-cmp010" },
{ QSB_CMP011, F, "error-limit-reached",
  "Fix the preceding errors. Increase --error-limit to see more.",
  DOC_BASE "qsb-cmp011" },
{ QSB_CMP012, E, "cross-compile-flags-incompatible",
  "Check that all extra_flags are compatible with the target triple.",
  DOC_BASE "qsb-cmp012" },

/* ── QSB-CSH  C# / dotnet driver ────────────────────────────────────────── */
{ QSB_CSH001, E, "dotnet-not-found",
  "Install the .NET SDK and ensure 'dotnet' is on PATH.",
  DOC_BASE "qsb-csh001" },
{ QSB_CSH002, W, "csc-not-found",
  "Install Mono or the .NET SDK; dotnet build is preferred.",
  DOC_BASE "qsb-csh002" },
{ QSB_CSH003, E, "dotnet-build-failed",
  "Check the MSBuild output above for specific compilation errors.",
  DOC_BASE "qsb-csh003" },
{ QSB_CSH004, E, "nuget-pack-failed",
  "Verify the .csproj / .nuspec is valid and all sources compile.",
  DOC_BASE "qsb-csh004" },
{ QSB_CSH005, E, "nuget-publish-failed",
  "Check credentials and the NuGet server URL.",
  DOC_BASE "qsb-csh005" },
{ QSB_CSH006, E, "invalid-dotnet-sdk",
  "Use a value like 'net8.0' or 'net6.0' for dotnet_sdk.",
  DOC_BASE "qsb-csh006" },
{ QSB_CSH007, E, "csproj-generation-failed",
  "Check write permissions on the output directory.",
  DOC_BASE "qsb-csh007" },
{ QSB_CSH008, E, "assembly-ref-not-found",
  "Add the missing assembly to link_libs or install the NuGet package.",
  DOC_BASE "qsb-csh008" },

/* ── QSB-DEP  Dependency-graph errors ───────────────────────────────────── */
{ QSB_DEP001, E, "dependency-cycle",
  "Remove the circular dependency between the listed modules.",
  DOC_BASE "qsb-dep001" },
{ QSB_DEP002, E, "dependency-not-found",
  "Add the missing module to the workspace or correct the name.",
  DOC_BASE "qsb-dep002" },
{ QSB_DEP003, E, "self-dependency",
  "A module cannot depend on itself; remove the self-reference.",
  DOC_BASE "qsb-dep003" },
{ QSB_DEP004, E, "topo-sort-arena-overflow",
  "Reduce the number of modules or increase the session arena size.",
  DOC_BASE "qsb-dep004" },
{ QSB_DEP005, E, "dep-graph-too-large",
  "The workspace contains more modules than the scheduler supports.",
  DOC_BASE "qsb-dep005" },
{ QSB_DEP006, W, "diamond-version-conflict",
  "Pin a single version of the conflicting dependency.",
  DOC_BASE "qsb-dep006" },

/* ── QSB-DRV  Driver dispatch ───────────────────────────────────────────── */
{ QSB_DRV001, E, "no-driver-for-language",
  "Check that the language field in build.qs is a supported value.",
  DOC_BASE "qsb-drv001" },
{ QSB_DRV002, E, "driver-unexpected-result",
  "This is likely an internal bug; please file an issue.",
  DOC_BASE "qsb-drv002" },
{ QSB_DRV003, E, "cross-compile-unsupported",
  "Use the Zig or Go drivers which have native cross-compile support.",
  DOC_BASE "qsb-drv003" },
{ QSB_DRV004, E, "output-type-unsupported",
  "Check the language/output-type compatibility table in the README.",
  DOC_BASE "qsb-drv004" },

/* ── QSB-EXT  Extension errors ───────────────────────────────────────────── */
{ QSB_EXT001, E, "extension-not-found",
  "Ensure the extension binary is on PATH or in QS_EXTENSION_PATH.",
  DOC_BASE "qsb-ext001" },
{ QSB_EXT002, E, "extension-handshake-failed",
  "Verify the extension implements the qs_build JSON-RPC protocol.",
  DOC_BASE "qsb-ext002" },
{ QSB_EXT003, E, "extension-error-response",
  "Check the extension's own error message for details.",
  DOC_BASE "qsb-ext003" },
{ QSB_EXT004, E, "extension-timeout",
  "Increase the extension timeout or check for a hang in the extension.",
  DOC_BASE "qsb-ext004" },
{ QSB_EXT005, E, "extension-json-malformed",
  "The extension returned invalid JSON; report this to the extension author.",
  DOC_BASE "qsb-ext005" },
{ QSB_EXT006, E, "extension-protocol-mismatch",
  "Update the extension to match the qs_build protocol version.",
  DOC_BASE "qsb-ext006" },
{ QSB_EXT007, E, "extension-crashed",
  "Run the extension manually to reproduce and diagnose the crash.",
  DOC_BASE "qsb-ext007" },

/* ── QSB-FS  Filesystem / path errors ───────────────────────────────────── */
{ QSB_FS001,  E, "path-too-long",       "Shorten the path.",                            DOC_BASE "qsb-fs001"  },
{ QSB_FS002,  E, "file-not-found",      "Check the path for typos.",                    DOC_BASE "qsb-fs002"  },
{ QSB_FS003,  E, "dir-not-found",       "Create the directory or correct the path.",    DOC_BASE "qsb-fs003"  },
{ QSB_FS004,  E, "permission-denied",   "Check file ownership and mode bits.",          DOC_BASE "qsb-fs004"  },
{ QSB_FS005,  E, "file-read-error",     "The file may be locked or on a failing disk.", DOC_BASE "qsb-fs005"  },
{ QSB_FS006,  E, "file-write-error",    "Check available disk space and permissions.",  DOC_BASE "qsb-fs006"  },
{ QSB_FS007,  E, "dir-create-failed",   "Check permissions on the parent directory.",   DOC_BASE "qsb-fs007"  },
{ QSB_FS008,  E, "dir-delete-failed",   "Ensure no files in the directory are locked.", DOC_BASE "qsb-fs008"  },
{ QSB_FS009,  E, "file-copy-failed",    "Check source permissions and disk space.",     DOC_BASE "qsb-fs009"  },
{ QSB_FS010,  E, "file-move-failed",    "Ensure source and destination are same FS.",   DOC_BASE "qsb-fs010"  },
{ QSB_FS011,  E, "symlink-failed",      "Check permissions or use a real file.",        DOC_BASE "qsb-fs011"  },
{ QSB_FS012,  E, "path-traversal",      "Paths must not escape the project root.",      DOC_BASE "qsb-fs012"  },
{ QSB_FS013,  E, "disk-full",           "Free disk space before building.",             DOC_BASE "qsb-fs013"  },
{ QSB_FS014,  W, "scan-depth-limit",    "Set a higher scan depth limit if needed.",     DOC_BASE "qsb-fs014"  },
{ QSB_FS015,  W, "file-empty",          "The file has no content; is this intended?",   DOC_BASE "qsb-fs015"  },
{ QSB_FS016,  E, "expected-file-got-dir","The path is a directory; expected a file.",   DOC_BASE "qsb-fs016"  },
{ QSB_FS017,  E, "expected-dir-got-file","The path is a file; expected a directory.",   DOC_BASE "qsb-fs017"  },
{ QSB_FS018,  W, "glob-no-matches",     "Widen the glob pattern or add source files.",  DOC_BASE "qsb-fs018"  },
{ QSB_FS019,  E, "stat-failed",         "The path may not exist or be inaccessible.",   DOC_BASE "qsb-fs019"  },
{ QSB_FS020,  E, "tmpfile-failed",      "Check TMPDIR / %TEMP% and disk space.",        DOC_BASE "qsb-fs020"  },

/* ── QSB-GO  Go driver errors ───────────────────────────────────────────── */
{ QSB_GO001, E, "go-not-found",
  "Install Go and ensure 'go' is on PATH. See https://go.dev/dl/",
  DOC_BASE "qsb-go001" },
{ QSB_GO002, E, "go-build-failed",
  "Check the go compiler output above for specific errors.",
  DOC_BASE "qsb-go002" },
{ QSB_GO003, E, "go-test-failed",
  "Run 'go test ./...' manually to see the full test output.",
  DOC_BASE "qsb-go003" },
{ QSB_GO004, E, "go-env-misconfigured",
  "Run 'go env' and correct GOPATH / GOROOT.",
  DOC_BASE "qsb-go004" },
{ QSB_GO005, E, "go-module-not-set",
  "Set go_module in build.qs to your module path (e.g. github.com/org/repo).",
  DOC_BASE "qsb-go005" },
{ QSB_GO006, E, "goos-goarch-unsupported",
  "Run 'go tool dist list' for supported GOOS/GOARCH pairs.",
  DOC_BASE "qsb-go006" },
{ QSB_GO007, E, "go-mod-tidy-failed",
  "Run 'go mod tidy' manually and commit the resulting go.sum.",
  DOC_BASE "qsb-go007" },
{ QSB_GO008, E, "cgo-c-compiler-missing",
  "Set CC to a valid C compiler or disable CGO with CGO_ENABLED=0.",
  DOC_BASE "qsb-go008" },
{ QSB_GO009, E, "go-install-failed",
  "Check the target GOPATH/bin is writable and the module is valid.",
  DOC_BASE "qsb-go009" },

/* ── QSB-INC  Incremental build errors ──────────────────────────────────── */
{ QSB_INC001, W, "depfile-not-found",
  "A full rebuild will be triggered for this source.",
  DOC_BASE "qsb-inc001" },
{ QSB_INC002, W, "depfile-parse-error",
  "Delete the .d file and rebuild; it may be corrupt.",
  DOC_BASE "qsb-inc002" },
{ QSB_INC003, W, "fingerprint-corrupted",
  "Delete the cache directory with --clean and rebuild.",
  DOC_BASE "qsb-inc003" },
{ QSB_INC004, E, "fingerprint-write-failed",
  "Check that the cache directory is writable.",
  DOC_BASE "qsb-inc004" },
{ QSB_INC005, W, "cache-dir-inaccessible",
  "Set QS_BUILD_CACHE_DIR to a writable directory.",
  DOC_BASE "qsb-inc005" },
{ QSB_INC006, N, "hash-mismatch-rebuilding",
  "Source has changed since last build; this is expected behaviour.",
  DOC_BASE "qsb-inc006" },
{ QSB_INC007, N, "flags-changed-invalidating",
  "Build flags changed; all affected objects will be rebuilt.",
  DOC_BASE "qsb-inc007" },
{ QSB_INC008, W, "cache-version-mismatch",
  "Cache created by a different qs_build version; running full rebuild.",
  DOC_BASE "qsb-inc008" },

/* ── QSB-INT  Internal / assertion errors ───────────────────────────────── */
{ QSB_INT001, F, "assertion-failed",
  "This is a bug in qs_build. Please file an issue with the full output.",
  DOC_BASE "qsb-int001" },
{ QSB_INT002, F, "null-pointer-guard",
  "Internal null-pointer check failed. Please file a bug report.",
  DOC_BASE "qsb-int002" },
{ QSB_INT003, F, "arena-overflow",
  "Increase the arena size or reduce the number of parallel jobs.",
  DOC_BASE "qsb-int003" },
{ QSB_INT004, F, "unreachable-reached",
  "Unreachable code was executed. Please file a bug report.",
  DOC_BASE "qsb-int004" },
{ QSB_INT005, F, "vector-oob",
  "Vector index out of bounds. Please file a bug report.",
  DOC_BASE "qsb-int005" },
{ QSB_INT006, F, "invalid-state",
  "State machine entered an invalid state. Please file a bug report.",
  DOC_BASE "qsb-int006" },
{ QSB_INT007, E, "not-implemented",
  "This code path is not yet implemented in this build of qs_build.",
  DOC_BASE "qsb-int007" },

/* ── QSB-JAV  Java driver errors ────────────────────────────────────────── */
{ QSB_JAV001, E, "javac-not-found",
  "Install the JDK (not just JRE) and add it to PATH.",
  DOC_BASE "qsb-jav001" },
{ QSB_JAV002, E, "java-not-found",
  "Install the JDK and ensure 'java' is on PATH.",
  DOC_BASE "qsb-jav002" },
{ QSB_JAV003, E, "javac-failed",
  "Fix the Java compilation errors shown above.",
  DOC_BASE "qsb-jav003" },
{ QSB_JAV004, E, "jar-packaging-failed",
  "Check the jar tool output and the contents of the class output directory.",
  DOC_BASE "qsb-jav004" },
{ QSB_JAV005, E, "manifest-classpath-invalid",
  "Class-Path entries in the JAR manifest must be relative paths.",
  DOC_BASE "qsb-jav005" },
{ QSB_JAV006, E, "java-version-unrecognised",
  "Use a value like '11', '17', or '21' for java_version.",
  DOC_BASE "qsb-jav006" },
{ QSB_JAV007, E, "classpath-entry-not-found",
  "Add the missing JAR or directory to the classpath.",
  DOC_BASE "qsb-jav007" },
{ QSB_JAV008, E, "maven-deploy-failed",
  "Check credentials and the maven_repo URL.",
  DOC_BASE "qsb-jav008" },
{ QSB_JAV009, E, "module-info-parse-error",
  "Ensure module-info.java is syntactically valid.",
  DOC_BASE "qsb-jav009" },

/* ── QSB-LEX  Manifest lexer errors ─────────────────────────────────────── */
{ QSB_LEX001, E, "unexpected-character",
  "Only ASCII printable characters are allowed in build.qs.",
  DOC_BASE "qsb-lex001" },
{ QSB_LEX002, E, "unterminated-string-literal",
  "Close the string with '\"' on the same logical line.",
  DOC_BASE "qsb-lex002" },
{ QSB_LEX003, E, "invalid-escape-sequence",
  "Supported escapes: \\n \\t \\\\ \\\".",
  DOC_BASE "qsb-lex003" },
{ QSB_LEX004, E, "number-literal-overflow",
  "Use a value that fits in a 64-bit unsigned integer.",
  DOC_BASE "qsb-lex004" },
{ QSB_LEX005, E, "invalid-identifier-char",
  "Identifiers may only contain [A-Za-z0-9_].",
  DOC_BASE "qsb-lex005" },
{ QSB_LEX006, E, "lex-io-error",
  "Ensure the manifest file exists and is readable.",
  DOC_BASE "qsb-lex006" },
{ QSB_LEX007, E, "manifest-too-large",
  "Split large manifests using workspace mode.",
  DOC_BASE "qsb-lex007" },
{ QSB_LEX008, E, "invalid-utf8",
  "The manifest must be encoded as UTF-8.",
  DOC_BASE "qsb-lex008" },

/* ── QSB-LNK  Linker errors ──────────────────────────────────────────────── */
{ QSB_LNK001, E, "linker-not-found",
  "Install a system linker (ar, ld, or link.exe) and add it to PATH.",
  DOC_BASE "qsb-lnk001" },
{ QSB_LNK002, E, "linker-nonzero-exit",
  "Fix the linker errors shown above (undefined symbols, etc.).",
  DOC_BASE "qsb-lnk002" },
{ QSB_LNK003, E, "no-objects-to-link",
  "Ensure the compile phase produced .o / .obj files.",
  DOC_BASE "qsb-lnk003" },
{ QSB_LNK004, E, "link-command-too-long",
  "Use a response file or reduce the number of object files.",
  DOC_BASE "qsb-lnk004" },
{ QSB_LNK005, E, "lib-dir-not-found",
  "Add the correct path to lib_dirs in the manifest.",
  DOC_BASE "qsb-lnk005" },
{ QSB_LNK006, E, "unresolved-symbol",
  "Add the missing library to link_libs.",
  DOC_BASE "qsb-lnk006" },
{ QSB_LNK007, E, "multiple-definition",
  "Check for duplicate implementations across translation units.",
  DOC_BASE "qsb-lnk007" },
{ QSB_LNK008, E, "output-binary-not-produced",
  "Check that the linker succeeded and the output path is writable.",
  DOC_BASE "qsb-lnk008" },
{ QSB_LNK009, W, "mixed-debug-release-objects",
  "Build all objects with the same profile to avoid CRT conflicts.",
  DOC_BASE "qsb-lnk009" },
{ QSB_LNK010, E, "lto-link-failed",
  "Disable LTO (--no-lto) or ensure all objects were compiled with -flto.",
  DOC_BASE "qsb-lnk010" },
{ QSB_LNK011, W, "missing-soname",
  "Pass -Wl,-soname,libfoo.so.1 for versioned shared libraries.",
  DOC_BASE "qsb-lnk011" },
{ QSB_LNK012, E, "link-timeout",
  "Large LTO or debug builds can be slow; increase the timeout.",
  DOC_BASE "qsb-lnk012" },

/* ── QSB-LTO  LTO errors ─────────────────────────────────────────────────── */
{ QSB_LTO001, W, "lto-not-supported",
  "Upgrade your compiler or disable LTO with enable_lto = false.",
  DOC_BASE "qsb-lto001" },
{ QSB_LTO002, W, "lto-debug-conflict",
  "Use -g0 when LTO is enabled for a release build.",
  DOC_BASE "qsb-lto002" },
{ QSB_LTO003, W, "thin-lto-cache-inaccessible",
  "Set QS_BUILD_CACHE_DIR to a writable directory.",
  DOC_BASE "qsb-lto003" },

/* ── QSB-MAN  Manifest parser errors ────────────────────────────────────── */
{ QSB_MAN001, E, "manifest-not-found",
  "Create a build.qs file in this directory or pass the path explicitly.",
  DOC_BASE "qsb-man001" },
{ QSB_MAN002, E, "manifest-empty",
  "Add at least one module { } block to the build.qs file.",
  DOC_BASE "qsb-man002" },
{ QSB_MAN003, E, "module-keyword-missing",
  "Wrap your fields in a 'module NAME { ... }' block.",
  DOC_BASE "qsb-man003" },
{ QSB_MAN004, E, "module-name-missing",
  "Add a name after the 'module' keyword.",
  DOC_BASE "qsb-man004" },
{ QSB_MAN005, E, "language-field-missing",
  "Add 'language = \"c\";' (or another language) to the module block.",
  DOC_BASE "qsb-man005" },
{ QSB_MAN006, E, "language-not-recognised",
  "Supported: c, cpp, csharp, java, python, go, ruby, rust, zig.",
  DOC_BASE "qsb-man006" },
{ QSB_MAN007, E, "output-type-not-recognised",
  "Supported: exe, dll, lib, app, qpkg, wheel, jar, gem, gobin.",
  DOC_BASE "qsb-man007" },
{ QSB_MAN008, W, "version-malformed",
  "Use semver format: MAJOR.MINOR.PATCH[-pre].",
  DOC_BASE "qsb-man008" },
{ QSB_MAN009, W, "sources-empty",
  "Add source files to the 'sources' list.",
  DOC_BASE "qsb-man009" },
{ QSB_MAN010, E, "sources-field-missing",
  "Add 'sources = [ \"src/main.c\" ];' to the module block.",
  DOC_BASE "qsb-man010" },
{ QSB_MAN011, W, "standard-not-recognised",
  "Use a known standard for the language (e.g. c17, c++20, net8.0).",
  DOC_BASE "qsb-man011" },
{ QSB_MAN012, E, "chunk-size-out-of-range",
  "Set chunk_size to a value between 1 and 65535.",
  DOC_BASE "qsb-man012" },
{ QSB_MAN013, W, "duplicate-module-block",
  "Each build.qs file should contain exactly one module block.",
  DOC_BASE "qsb-man013" },
{ QSB_MAN014, E, "field-wrong-type",
  "Check the build.qs reference for the expected type of this field.",
  DOC_BASE "qsb-man014" },
{ QSB_MAN015, W, "unrecognised-field",
  "Remove or correct the unrecognised field name.",
  DOC_BASE "qsb-man015" },
{ QSB_MAN016, E, "pch-header-path-invalid",
  "Provide a valid relative path for pch_header.",
  DOC_BASE "qsb-man016" },
{ QSB_MAN017, E, "go-module-invalid",
  "Use a valid Go module path like 'github.com/org/repo'.",
  DOC_BASE "qsb-man017" },

/* ── QSB-MIG  Migrator errors ────────────────────────────────────────────── */
{ QSB_MIG001, E, "source-build-file-not-found",
  "Run migrate from the directory containing CMakeLists.txt / Cargo.toml / etc.",
  DOC_BASE "qsb-mig001" },
{ QSB_MIG002, E, "unsupported-build-system",
  "Supported: CMake, Cargo, go.mod, Makefile (basic).",
  DOC_BASE "qsb-mig002" },
{ QSB_MIG003, W, "migration-produced-empty-manifest",
  "The source build file could not be parsed; edit build.qs manually.",
  DOC_BASE "qsb-mig003" },
{ QSB_MIG004, W, "cmake-variable-expansion",
  "CMake variables were not expanded; replace them manually in build.qs.",
  DOC_BASE "qsb-mig004" },
{ QSB_MIG005, E, "cargo-toml-parse-failed",
  "Ensure Cargo.toml is valid TOML.",
  DOC_BASE "qsb-mig005" },
{ QSB_MIG006, E, "go-mod-parse-failed",
  "Ensure go.mod is a valid Go module file.",
  DOC_BASE "qsb-mig006" },
{ QSB_MIG007, E, "migration-write-failed",
  "Check write permissions on the directory.",
  DOC_BASE "qsb-mig007" },
{ QSB_MIG008, W, "ambiguous-project-structure",
  "Multiple build systems detected; pick one and run migrate again.",
  DOC_BASE "qsb-mig008" },

/* ── QSB-MON  Phase-monitor errors ──────────────────────────────────────── */
{ QSB_MON001, W, "telemetry-file-open-failed",
  "Check the path specified in QS_BUILD_LOG.",
  DOC_BASE "qsb-mon001" },
{ QSB_MON002, E, "phase-name-empty",
  "Internal error: phase_begin was called with a NULL name.",
  DOC_BASE "qsb-mon002" },
{ QSB_MON003, W, "phase-end-before-begin",
  "Mismatched phase_end call in the build pipeline.",
  DOC_BASE "qsb-mon003" },
{ QSB_MON004, W, "too-many-concurrent-phases",
  "Internal limit exceeded; nested phase tracking is limited.",
  DOC_BASE "qsb-mon004" },

/* ── QSB-NET  Remote-cache / HTTP errors ────────────────────────────────── */
{ QSB_NET001, W, "remote-cache-url-not-set",
  "Set QS_REMOTE_CACHE_URL to enable the remote cache.",
  DOC_BASE "qsb-net001" },
{ QSB_NET002, W, "dns-resolution-failed",
  "Check network connectivity and the cache server hostname.",
  DOC_BASE "qsb-net002" },
{ QSB_NET003, W, "connection-refused",
  "Verify the remote cache server is running and the port is correct.",
  DOC_BASE "qsb-net003" },
{ QSB_NET004, W, "http-timeout",
  "Set QS_BUILD_NO_CACHE=1 to build without the remote cache.",
  DOC_BASE "qsb-net004" },
{ QSB_NET005, W, "http-bad-status",
  "Check the server logs for the cause of the non-200 response.",
  DOC_BASE "qsb-net005" },
{ QSB_NET006, W, "socket-error",
  "Check network stability and firewall rules.",
  DOC_BASE "qsb-net006" },
{ QSB_NET007, W, "response-truncated",
  "The cached object may be corrupt; a local build will proceed.",
  DOC_BASE "qsb-net007" },
{ QSB_NET008, W, "cache-auth-failed",
  "Check QS_REMOTE_CACHE_TOKEN.",
  DOC_BASE "qsb-net008" },
{ QSB_NET009, N, "cache-miss",
  "Object not in remote cache; compiling locally.",
  DOC_BASE "qsb-net009" },
{ QSB_NET010, W, "cache-server-error",
  "The remote cache returned a 5xx error; building locally.",
  DOC_BASE "qsb-net010" },
{ QSB_NET011, W, "socket-create-failed",
  "Check system socket limits (ulimit -n).",
  DOC_BASE "qsb-net011" },
{ QSB_NET012, W, "https-not-supported",
  "The remote cache client only supports plain HTTP. Use a proxy.",
  DOC_BASE "qsb-net012" },

/* ── QSB-OOM  Out-of-memory errors ──────────────────────────────────────── */
{ QSB_OOM001, F, "system-oom",
  "Free system memory or reduce the number of parallel jobs.",
  DOC_BASE "qsb-oom001" },
{ QSB_OOM002, F, "scratch-arena-overflow",
  "The scratch arena is sized at build time; file a bug if this triggers.",
  DOC_BASE "qsb-oom002" },
{ QSB_OOM003, F, "vector-grow-failed",
  "Free system memory or reduce the number of source files.",
  DOC_BASE "qsb-oom003" },
{ QSB_OOM004, F, "intern-table-full",
  "The string intern table is at capacity; reduce unique string count.",
  DOC_BASE "qsb-oom004" },

/* ── QSB-PCH  PCH errors ──────────────────────────────────────────────────── */
{ QSB_PCH001, E, "pch-compile-failed",
  "Fix errors in the PCH header file.",
  DOC_BASE "qsb-pch001" },
{ QSB_PCH002, E, "pch-header-not-found",
  "Check the pch_header path in the manifest.",
  DOC_BASE "qsb-pch002" },
{ QSB_PCH003, E, "pch-output-not-produced",
  "Check the compiler output above and ensure the output directory is writable.",
  DOC_BASE "qsb-pch003" },
{ QSB_PCH004, W, "pch-not-supported",
  "Use --no-pch to disable precompiled headers for this toolchain.",
  DOC_BASE "qsb-pch004" },
{ QSB_PCH005, N, "pch-invalidated",
  "Flags changed since the PCH was compiled; it will be rebuilt.",
  DOC_BASE "qsb-pch005" },
{ QSB_PCH006, W, "pch-pragma-once-error",
  "Ensure the PCH header uses #pragma once or include guards.",
  DOC_BASE "qsb-pch006" },
{ QSB_PCH007, E, "auto-pch-write-failed",
  "Check write permissions on the output directory.",
  DOC_BASE "qsb-pch007" },

/* ── QSB-PIP  Pipeline errors ────────────────────────────────────────────── */
{ QSB_PIP001, E, "pipeline-phase-failed",
  "See the errors above for the specific phase that failed.",
  DOC_BASE "qsb-pip001" },
{ QSB_PIP002, E, "output-dir-create-failed",
  "Check permissions on the parent directory of --out.",
  DOC_BASE "qsb-pip002" },
{ QSB_PIP003, E, "clean-failed",
  "Delete the output directory manually: rm -rf ./out",
  DOC_BASE "qsb-pip003" },
{ QSB_PIP004, E, "hook-nonzero-exit",
  "Fix the hook script. Set it executable and check its interpreter.",
  DOC_BASE "qsb-pip004" },
{ QSB_PIP005, E, "no-modules-found",
  "Ensure the workspace directory contains subdirectories with build.qs files.",
  DOC_BASE "qsb-pip005" },
{ QSB_PIP006, E, "module-order-unresolvable",
  "Check for dependency cycles between workspace modules.",
  DOC_BASE "qsb-pip006" },
{ QSB_PIP007, W, "dry-run-with-invalid-manifest",
  "Fix the manifest errors before a real build will succeed.",
  DOC_BASE "qsb-pip007" },
{ QSB_PIP008, E, "asset-pipeline-failed",
  "Check that the required asset tools (glslc, etc.) are on PATH.",
  DOC_BASE "qsb-pip008" },
{ QSB_PIP009, E, "test-phase-failed",
  "One or more tests failed. See the test output above.",
  DOC_BASE "qsb-pip009" },
{ QSB_PIP010, E, "publish-phase-failed",
  "Check credentials and network connectivity for the publish target.",
  DOC_BASE "qsb-pip010" },

/* ── QSB-PKG  Packager / .qpkg errors ───────────────────────────────────── */
{ QSB_PKG001, E, "qpkg-header-write-failed",   "Check disk space and output directory permissions.", DOC_BASE "qsb-pkg001" },
{ QSB_PKG002, E, "qpkg-entry-write-failed",    "Check disk space.",                                 DOC_BASE "qsb-pkg002" },
{ QSB_PKG003, E, "qpkg-open-failed",           "Check the output path and permissions.",            DOC_BASE "qsb-pkg003" },
{ QSB_PKG004, E, "qpkg-index-write-failed",    "Check disk space.",                                 DOC_BASE "qsb-pkg004" },
{ QSB_PKG005, E, "qpkg-checksum-mismatch",     "The archive is corrupt; rebuild it.",               DOC_BASE "qsb-pkg005" },
{ QSB_PKG006, E, "qpkg-bad-magic",             "The file is not a valid .qpkg archive.",            DOC_BASE "qsb-pkg006" },
{ QSB_PKG007, E, "qpkg-version-unsupported",   "Use a qs_build version that supports this .qpkg.", DOC_BASE "qsb-pkg007" },
{ QSB_PKG008, E, "qpkg-index-corrupt",         "The archive index is corrupt; rebuild it.",         DOC_BASE "qsb-pkg008" },
{ QSB_PKG009, E, "qpkg-too-many-entries",      "Split the package into smaller archives.",          DOC_BASE "qsb-pkg009" },
{ QSB_PKG010, E, "qpkg-v2-index-write-failed", "Check disk space.",                                 DOC_BASE "qsb-pkg010" },
{ QSB_PKG020, E, "qpkg-verify-not-found",      "Provide a valid path to a .qpkg file.",             DOC_BASE "qsb-pkg020" },
{ QSB_PKG021, E, "qpkg-verify-read-error",     "The file may be locked or on a failing disk.",      DOC_BASE "qsb-pkg021" },
{ QSB_PKG022, E, "qpkg-entry-name-malformed",  "Entry names must be relative paths.",               DOC_BASE "qsb-pkg022" },

/* ── QSB-PLG  Plugin errors ───────────────────────────────────────────────── */
{ QSB_PLG001, E, "plugin-not-found",
  "Ensure the .so / .dll is in <exe_dir>/plugins/ or QS_PLUGIN_PATH.",
  DOC_BASE "qsb-plg001" },
{ QSB_PLG002, E, "dlopen-failed",
  "Inspect the dynamic linker error with 'ldd plugin.so'.",
  DOC_BASE "qsb-plg002" },
{ QSB_PLG003, E, "plugin-init-not-found",
  "Export 'qs_plugin_info_t *qs_plugin_init(qs_plugin_host_t*)' from the plugin.",
  DOC_BASE "qsb-plg003" },
{ QSB_PLG004, E, "plugin-api-version-mismatch",
  "Rebuild the plugin against the current qs_plugin_api.h.",
  DOC_BASE "qsb-plg004" },
{ QSB_PLG005, E, "plugin-init-null",
  "The plugin's qs_plugin_init() must return a valid info pointer.",
  DOC_BASE "qsb-plg005" },
{ QSB_PLG006, E, "plugin-name-empty",
  "Set name and version fields in the plugin's qs_plugin_info_t.",
  DOC_BASE "qsb-plg006" },
{ QSB_PLG007, E, "plugin-hook-register-failed",
  "Ensure the hook type is supported by the current api_version.",
  DOC_BASE "qsb-plg007" },
{ QSB_PLG008, E, "plugin-hook-raised",
  "A plugin hook crashed. Disable the plugin to isolate the issue.",
  DOC_BASE "qsb-plg008" },
{ QSB_PLG009, W, "plugin-dir-not-found",
  "Create the plugins directory or adjust QS_PLUGIN_PATH.",
  DOC_BASE "qsb-plg009" },
{ QSB_PLG010, W, "plugin-cap-reached",
  "Reduce the number of loaded plugins.",
  DOC_BASE "qsb-plg010" },

/* ── QSB-PRB  Toolchain-probe errors ────────────────────────────────────── */
{ QSB_PRB001, E, "compiler-not-found",
  "Install the required compiler and add it to PATH.",
  DOC_BASE "qsb-prb001" },
{ QSB_PRB002, W, "compiler-version-query-failed",
  "Run the compiler with --version manually to debug.",
  DOC_BASE "qsb-prb002" },
{ QSB_PRB003, E, "compiler-too-old",
  "Upgrade your compiler to support the requested standard.",
  DOC_BASE "qsb-prb003" },
{ QSB_PRB004, W, "multiple-compilers",
  "Set CC / CXX environment variables to select one explicitly.",
  DOC_BASE "qsb-prb004" },
{ QSB_PRB005, E, "sysroot-not-found",
  "Install the cross-compile sysroot or correct the path.",
  DOC_BASE "qsb-prb005" },
{ QSB_PRB006, E, "cross-toolchain-not-found",
  "Install the cross-compile toolchain for the target triple.",
  DOC_BASE "qsb-prb006" },
{ QSB_PRB007, W, "probe-timeout",
  "Compiler probing timed out; using cached probe result.",
  DOC_BASE "qsb-prb007" },
{ QSB_PRB008, E, "linker-probe-failed",
  "Ensure ar / ld / link.exe is installed.",
  DOC_BASE "qsb-prb008" },
{ QSB_PRB009, W, "assembler-not-found",
  "Install an assembler (as / nasm / yasm) to build assembly sources.",
  DOC_BASE "qsb-prb009" },

/* ── QSB-PRC  Subprocess / process errors ───────────────────────────────── */
{ QSB_PRC001, E, "fork-failed",         "System may be out of process slots (ulimit -u).", DOC_BASE "qsb-prc001" },
{ QSB_PRC002, E, "pipe-failed",         "System may be out of file descriptors.",          DOC_BASE "qsb-prc002" },
{ QSB_PRC003, E, "waitpid-failed",      "Internal process management error.",              DOC_BASE "qsb-prc003" },
{ QSB_PRC004, E, "process-killed",      "The child process was killed by a signal.",       DOC_BASE "qsb-prc004" },
{ QSB_PRC005, W, "stdout-overflow",     "Increase QS_PROC_STDOUT_MAX.",                   DOC_BASE "qsb-prc005" },
{ QSB_PRC006, W, "stderr-overflow",     "Increase QS_PROC_STDERR_MAX.",                   DOC_BASE "qsb-prc006" },
{ QSB_PRC007, E, "process-timeout",     "Increase the build timeout or split the build.", DOC_BASE "qsb-prc007" },
{ QSB_PRC008, E, "exec-failed",         "Verify the executable path and permissions.",    DOC_BASE "qsb-prc008" },
{ QSB_PRC009, E, "command-too-long",    "Reduce the argument list or use response files.", DOC_BASE "qsb-prc009" },

/* ── QSB-PYT  Python driver errors ──────────────────────────────────────── */
{ QSB_PYT001, E, "python-not-found",
  "Install Python 3 and ensure 'python3' is on PATH.",
  DOC_BASE "qsb-pyt001" },
{ QSB_PYT002, E, "pip-not-found",
  "Install pip: python3 -m ensurepip --upgrade",
  DOC_BASE "qsb-pyt002" },
{ QSB_PYT003, E, "pyproject-missing",
  "Add a pyproject.toml or setup.py to the project root.",
  DOC_BASE "qsb-pyt003" },
{ QSB_PYT004, E, "wheel-build-failed",
  "Check the pip/build output above for specific errors.",
  DOC_BASE "qsb-pyt004" },
{ QSB_PYT005, E, "pip-install-failed",
  "Check the pip output and verify the package is valid.",
  DOC_BASE "qsb-pyt005" },
{ QSB_PYT006, E, "twine-upload-failed",
  "Check credentials and the PyPI index URL.",
  DOC_BASE "qsb-pyt006" },
{ QSB_PYT007, E, "python-version-invalid",
  "Use a format like '3.12' for python_version.",
  DOC_BASE "qsb-pyt007" },
{ QSB_PYT008, E, "virtualenv-failed",
  "Ensure virtualenv is installed: pip install virtualenv",
  DOC_BASE "qsb-pyt008" },

/* ── QSB-RB   Remote-build / remote-cache client errors ─────────────────── */
{ QSB_RB001, W, "cache-put-too-large",
  "The object exceeds the server's maximum upload size.",
  DOC_BASE "qsb-rb001" },
{ QSB_RB002, W, "cache-token-expired",
  "Refresh QS_REMOTE_CACHE_TOKEN.",
  DOC_BASE "qsb-rb002" },
{ QSB_RB003, W, "cache-key-collision",
  "Hash collision in the remote cache; the object will be rebuilt.",
  DOC_BASE "qsb-rb003" },
{ QSB_RB004, W, "cache-integrity-failed",
  "Fetched object checksum did not match; rebuilding locally.",
  DOC_BASE "qsb-rb004" },

/* ── QSB-REF  Reflection extractor errors ───────────────────────────────── */
{ QSB_REF001, E, "reflect-json-write-failed", "Check write permissions on the output directory.", DOC_BASE "qsb-ref001" },
{ QSB_REF002, W, "reflect-macro-malformed",   "QS_REFLECT() must have a non-empty name string.", DOC_BASE "qsb-ref002" },
{ QSB_REF003, W, "reflect-duplicate-symbol",  "Use unique names in QS_REFLECT() annotations.",   DOC_BASE "qsb-ref003" },
{ QSB_REF004, E, "reflect-scan-failed",        "Check that sources are readable.",                DOC_BASE "qsb-ref004" },

/* ── QSB-RST  Rust driver errors ─────────────────────────────────────────── */
{ QSB_RST001, E, "cargo-not-found",
  "Install Rust via rustup: https://rustup.rs/",
  DOC_BASE "qsb-rst001" },
{ QSB_RST002, W, "rustc-not-found",
  "Install rustc or use cargo mode (preferred).",
  DOC_BASE "qsb-rst002" },
{ QSB_RST003, E, "cargo-build-failed",
  "Fix the Rust compilation errors shown above.",
  DOC_BASE "qsb-rst003" },
{ QSB_RST004, E, "cargo-toml-not-found",
  "Add a Cargo.toml to the module directory.",
  DOC_BASE "qsb-rst004" },
{ QSB_RST005, E, "rust-edition-not-recognised",
  "Supported editions: 2015, 2018, 2021.",
  DOC_BASE "qsb-rst005" },
{ QSB_RST006, E, "rust-target-not-installed",
  "Run: rustup target add <target>",
  DOC_BASE "qsb-rst006" },
{ QSB_RST007, E, "cargo-publish-failed",
  "Check credentials and the registry URL.",
  DOC_BASE "qsb-rst007" },
{ QSB_RST008, W, "rustfmt-clippy-failed",
  "Fix the rustfmt / clippy warnings or disable them in the manifest.",
  DOC_BASE "qsb-rst008" },

/* ── QSB-RUB  Ruby driver errors ────────────────────────────────────────── */
{ QSB_RUB001, E, "ruby-not-found",    "Install Ruby and add 'ruby' to PATH.",       DOC_BASE "qsb-rub001" },
{ QSB_RUB002, E, "gem-not-found",     "Install gem: it ships with Ruby >= 1.9.",    DOC_BASE "qsb-rub002" },
{ QSB_RUB003, E, "ruby-syntax-error", "Fix the Ruby syntax error shown above.",     DOC_BASE "qsb-rub003" },
{ QSB_RUB004, E, "gem-build-failed",  "Check the gemspec and source files.",        DOC_BASE "qsb-rub004" },
{ QSB_RUB005, E, "gem-push-failed",   "Check credentials and the RubyGems URL.",    DOC_BASE "qsb-rub005" },
{ QSB_RUB006, E, "gemspec-not-found", "Add a .gemspec file or set ruby_gemspec.",   DOC_BASE "qsb-rub006" },
{ QSB_RUB007, E, "bundle-failed",     "Run 'bundle install' manually to diagnose.", DOC_BASE "qsb-rub007" },

/* ── QSB-SCH  Scheduler errors ───────────────────────────────────────────── */
{ QSB_SCH001, E, "scheduler-stalled",       "Internal scheduler error; please file a bug.", DOC_BASE "qsb-sch001" },
{ QSB_SCH002, E, "job-unexpected-error",    "Check the job error code in verbose output.",  DOC_BASE "qsb-sch002" },
{ QSB_SCH003, E, "job-no-compile-unit",     "Internal error; please file a bug report.",    DOC_BASE "qsb-sch003" },
{ QSB_SCH004, W, "dep-not-satisfied",       "Dependency ordering issue; retrying.",         DOC_BASE "qsb-sch004" },
{ QSB_SCH005, F, "deadlock-detected",       "Internal deadlock; reduce --jobs or file bug.",DOC_BASE "qsb-sch005" },

/* ── QSB-SCN  Source scanner errors ─────────────────────────────────────── */
{ QSB_SCN001, E, "source-dir-not-found",  "Check the sources directory path in the manifest.", DOC_BASE "qsb-scn001" },
{ QSB_SCN002, W, "source-scan-empty",     "No source files found; add files or fix the path.", DOC_BASE "qsb-scn002" },
{ QSB_SCN003, W, "source-ext-unknown",    "Add the extension to the language driver filter.",   DOC_BASE "qsb-scn003" },
{ QSB_SCN004, W, "scan-recursion-limit",  "Reduce directory nesting depth.",                    DOC_BASE "qsb-scn004" },
{ QSB_SCN005, E, "source-list-too-large", "Split the module into smaller modules.",             DOC_BASE "qsb-scn005" },

/* ── QSB-SCR  Scripting / hook errors ───────────────────────────────────── */
{ QSB_SCR001, E, "hook-script-not-found", "Check the script path in .qsbuildrc or the manifest.", DOC_BASE "qsb-scr001" },
{ QSB_SCR002, E, "hook-nonzero-exit",     "Fix the hook script; non-zero exit aborts the build.", DOC_BASE "qsb-scr002" },
{ QSB_SCR003, E, "hook-timeout",          "Increase hook timeout or speed up the script.",        DOC_BASE "qsb-scr003" },
{ QSB_SCR004, E, "hook-interpreter-missing","Install the script interpreter (bash, python3, etc.)",DOC_BASE "qsb-scr004" },
{ QSB_SCR005, W, "hook-env-inject-failed","Build environment variables could not be set for hook.",DOC_BASE "qsb-scr005" },

/* ── QSB-SER  Serialisation errors ─────────────────────────────────────── */
{ QSB_SER001, E, "checksum-unsupported",  "Only xxhash64 is supported for .qpkg checksums.", DOC_BASE "qsb-ser001" },
{ QSB_SER002, E, "index-buffer-overflow", "Reduce the number of files in the package.",      DOC_BASE "qsb-ser002" },
{ QSB_SER003, E, "entry-count-overflow",  "Split the package; entry count exceeds UINT32.",  DOC_BASE "qsb-ser003" },
{ QSB_SER004, E, "alignment-violation",   "Internal serialiser alignment bug; file a report.", DOC_BASE "qsb-ser004" },

/* ── QSB-SHD  Shader compiler errors ────────────────────────────────────── */
{ QSB_SHD001, E, "shader-compiler-not-found",
  "Install glslc (Vulkan SDK), dxc (DirectX), or xcrun for Metal.",
  DOC_BASE "qsb-shd001" },
{ QSB_SHD002, E, "shader-compile-failed",
  "Fix the GLSL / HLSL / MSL errors shown above.",
  DOC_BASE "qsb-shd002" },
{ QSB_SHD003, E, "shader-source-not-found",
  "Check the shader source path in the asset manifest.",
  DOC_BASE "qsb-shd003" },
{ QSB_SHD004, E, "shader-stage-unknown",
  "Supported stages: vert, frag, comp, geom, tesc, tese.",
  DOC_BASE "qsb-shd004" },
{ QSB_SHD005, E, "shader-output-not-produced",
  "Check output directory permissions.",
  DOC_BASE "qsb-shd005" },
{ QSB_SHD006, W, "shader-include-not-found",
  "Add the shader include directory to the asset pipeline config.",
  DOC_BASE "qsb-shd006" },

/* ── QSB-SYS  System capability errors ──────────────────────────────────── */
{ QSB_SYS001, E, "syscall-unavailable",   "Upgrade the OS or use a compatible build host.", DOC_BASE "qsb-sys001" },
{ QSB_SYS002, W, "cpu-count-unknown",     "Defaulting to 1 parallel job.",                  DOC_BASE "qsb-sys002" },
{ QSB_SYS003, W, "low-memory",            "Close other applications to free RAM.",          DOC_BASE "qsb-sys003" },
{ QSB_SYS004, E, "posix-only-feature",    "This feature requires a POSIX-compatible OS.",   DOC_BASE "qsb-sys004" },
{ QSB_SYS005, E, "win32-only-feature",    "This feature requires Windows.",                 DOC_BASE "qsb-sys005" },
{ QSB_SYS006, W, "clock-error",           "Timing information may be inaccurate.",          DOC_BASE "qsb-sys006" },

/* ── QSB-THR  Thread-pool errors ────────────────────────────────────────── */
{ QSB_THR001, E, "thread-create-failed",  "System thread limit reached (ulimit -u).",        DOC_BASE "qsb-thr001" },
{ QSB_THR002, F, "mutex-init-failed",     "System resource limit reached.",                  DOC_BASE "qsb-thr002" },
{ QSB_THR003, F, "condvar-init-failed",   "System resource limit reached.",                  DOC_BASE "qsb-thr003" },
{ QSB_THR004, E, "thread-join-timeout",   "A worker thread is stuck; use --jobs 1 to debug.",DOC_BASE "qsb-thr004" },
{ QSB_THR005, F, "worker-crashed",        "A worker thread crashed; reduce --jobs.",         DOC_BASE "qsb-thr005" },
{ QSB_THR006, W, "job-queue-overflow",    "Too many pending jobs; reduce --jobs.",           DOC_BASE "qsb-thr006" },
{ QSB_THR007, F, "pool-not-initialised",  "Internal error: pool used before init.",          DOC_BASE "qsb-thr007" },

/* ── QSB-TST  Test-runner errors ────────────────────────────────────────── */
{ QSB_TST001, E, "test-binary-not-found", "Build succeeded but the test binary is missing.", DOC_BASE "qsb-tst001" },
{ QSB_TST002, E, "test-nonzero-exit",     "One or more tests failed; see TAP output above.", DOC_BASE "qsb-tst002" },
{ QSB_TST003, W, "tap-malformed",         "The test binary produced non-TAP output.",        DOC_BASE "qsb-tst003" },
{ QSB_TST004, E, "test-timeout",          "Increase the test timeout or fix a hung test.",   DOC_BASE "qsb-tst004" },
{ QSB_TST005, W, "test-count-mismatch",   "The TAP plan count doesn't match actual tests.",  DOC_BASE "qsb-tst005" },
{ QSB_TST006, W, "no-test-sources",       "Add test source files to the manifest.",          DOC_BASE "qsb-tst006" },
{ QSB_TST007, E, "test-exec-failed",      "Ensure the test binary has execute permission.",  DOC_BASE "qsb-tst007" },

/* ── QSB-VAL  Manifest validator errors ─────────────────────────────────── */
{ QSB_VAL001, E, "source-not-found",       "Add the file or remove it from sources.",           DOC_BASE "qsb-val001" },
{ QSB_VAL002, W, "duplicate-source",       "Remove the duplicate source entry.",                DOC_BASE "qsb-val002" },
{ QSB_VAL003, E, "output-type-invalid",    "Consult the language/output-type table in the README.", DOC_BASE "qsb-val003" },
{ QSB_VAL004, E, "pch-header-not-found",   "Correct the pch_header path.",                     DOC_BASE "qsb-val004" },
{ QSB_VAL005, W, "include-dir-not-found",  "Create the directory or remove it from include_dirs.", DOC_BASE "qsb-val005" },
{ QSB_VAL006, N, "lto-debug-warning",      "Use enable_lto = false for full debug builds.",    DOC_BASE "qsb-val006" },
{ QSB_VAL007, W, "dep-name-whitespace",    "Remove whitespace from dependency names.",         DOC_BASE "qsb-val007" },
{ QSB_VAL008, W, "define-no-value",        "Defines with '=' must have a value: FOO=1",        DOC_BASE "qsb-val008" },
{ QSB_VAL009, W, "chunk-size-too-large",   "chunk_size > source count; chunking has no effect.",DOC_BASE "qsb-val009" },
{ QSB_VAL010, E, "module-name-invalid",    "Module names may only contain [A-Za-z0-9_-].",     DOC_BASE "qsb-val010" },
{ QSB_VAL011, W, "lib-dir-not-found",      "Add the directory or remove it from lib_dirs.",    DOC_BASE "qsb-val011" },
{ QSB_VAL012, W, "version-not-semver",     "Use MAJOR.MINOR.PATCH format for the version.",   DOC_BASE "qsb-val012" },
{ QSB_VAL013, E, "test-source-not-found",  "Check the test file path.",                        DOC_BASE "qsb-val013" },
{ QSB_VAL014, W, "out-dir-absolute",       "Use a relative path for out_dir in the manifest.", DOC_BASE "qsb-val014" },
{ QSB_VAL015, W, "extra-flags-injection-risk","Avoid shell metacharacters in extra_flags.",    DOC_BASE "qsb-val015" },

/* ── QSB-WRK  Workspace errors ───────────────────────────────────────────── */
{ QSB_WRK001, E, "workspace-root-not-found", "Run qs_build from a directory containing modules.", DOC_BASE "qsb-wrk001" },
{ QSB_WRK002, E, "no-modules-in-workspace",  "Ensure subdirectories contain build.qs files.",     DOC_BASE "qsb-wrk002" },
{ QSB_WRK003, W, "workspace-module-cap",     "Reduce the number of modules or increase the cap.", DOC_BASE "qsb-wrk003" },
{ QSB_WRK004, E, "duplicate-module-name",    "Ensure every module has a unique name field.",       DOC_BASE "qsb-wrk004" },
{ QSB_WRK005, E, "workspace-order-failed",   "Check for dependency cycles between modules.",       DOC_BASE "qsb-wrk005" },

/* ── QSB-ZIG  Zig driver errors ──────────────────────────────────────────── */
{ QSB_ZIG001, E, "zig-not-found",
  "Install Zig and ensure 'zig' is on PATH. See https://ziglang.org/download/",
  DOC_BASE "qsb-zig001" },
{ QSB_ZIG002, E, "zig-build-failed",
  "Fix the Zig compilation errors shown above.",
  DOC_BASE "qsb-zig002" },
{ QSB_ZIG003, E, "build-zig-gen-failed",
  "Check write permissions on the module directory.",
  DOC_BASE "qsb-zig003" },
{ QSB_ZIG004, E, "zig-cc-failed",
  "Zig cc fallback failed. Ensure zig cc supports the target.",
  DOC_BASE "qsb-zig004" },
{ QSB_ZIG005, E, "zig-target-not-recognised",
  "Run 'zig targets' for a list of supported targets.",
  DOC_BASE "qsb-zig005" },
{ QSB_ZIG006, E, "zig-too-old",
  "Upgrade Zig to 0.12 or later.",
  DOC_BASE "qsb-zig006" },
{ QSB_ZIG007, E, "zig-translate-c-failed",
  "Check that the C source is valid and headers are accessible.",
  DOC_BASE "qsb-zig007" },

/* ── Sentinel ────────────────────────────────────────────────────────────── */
{ NULL, (qs_severity_t)0, NULL, NULL, NULL }
};

#undef E
#undef W
#undef N
#undef F

/* ── Public API implementation ───────────────────────────────────────────── */

const qs_error_entry_t *qs_error_catalog_ptr(void) {
    return CATALOG;
}

qs_size_t qs_error_count(void) {
    qs_size_t n = 0;
    while (CATALOG[n].code) n++;
    return n;
}

const qs_error_entry_t *qs_error_lookup(const char *code) {
    if (!code) return NULL;
    for (const qs_error_entry_t *e = CATALOG; e->code; e++) {
        if (strcmp(e->code, code) == 0) return e;
    }
    return NULL;
}

void qs_error_emit(qs_diag_engine_t *engine,
                   qs_arena_t       *arena,
                   const char       *code,
                   qs_severity_t     sev,
                   const char       *tool,
                   qs_loc_t          loc,
                   const char       *message) {
    const qs_error_entry_t *entry = qs_error_lookup(code);

    qs_diag_t d;
    memset(&d, 0, sizeof(d));

    d.code    = qs_str_from_cstr(code ? code : "");
    d.tool    = qs_str_from_cstr(tool ? tool : "qs_build");
    d.loc     = loc;

    /* Severity: caller may pass (qs_severity_t)-1 to use catalogue default */
    d.sev = ((int)sev == -1)
            ? (entry ? entry->default_sev : QS_SEV_ERROR)
            : sev;

    /* Message: caller may pass NULL to use the catalogue name */
    if (message) {
        d.message = qs_str_from_cstr(message);
    } else if (entry && entry->name) {
        d.message = qs_str_from_cstr(entry->name);
    } else {
        d.message = qs_str_from_cstr("(no message)");
    }

    /* Populate hint and URL from the catalogue */
    if (entry) {
        if (entry->hint) d.hint = qs_str_from_cstr(entry->hint);
        if (entry->url)  d.url  = qs_str_from_cstr(entry->url);
    }

    qs_diag_emit(engine, d);

    QS_UNUSED(arena); /* reserved for future arena-duped strings */
}
