/*
 * documentation/docs_gen.c — Auto-documentation generator.
 *
 * Scans source files for doc-comment blocks and generates:
 *   - Markdown files per module
 *   - JSON API manifest (used by Forge:Visuals block registry)
 *
 * Doc-comment format (C/C++):
 *   /** QS_DOC
 *    * @brief  Short description
 *    * @param  name  Description
 *    * @return Description
 *    * @example
 *    *   code here
 *    *|/
 *
 * Forge:Visuals reads the JSON manifest to populate visual blocks
 * with documentation, parameter types, and examples.
 */
#include "../core/include/qs_types.h"
#include "../core/include/qs_arena.h"
#include "../core/include/qs_manifest.h"
#include "../core/include/qs_fs.h"
#include "../core/include/qs_vec.h"
#include <stdio.h>
#include <string.h>
#include <ctype.h>

typedef struct {
    char *brief;
    char *params[16];   /* "name: description" strings */
    qs_size_t param_count;
    char *returns;
    char *example;
    char *source_file;
    qs_u64 source_line;
    char *symbol_name;  /* extracted from next non-empty line after comment */
} qs_doc_entry_t;

QS_VEC_DECL(qs_doc_entry_t, qs_doc_vec)

static void trim_leading(char *s) {
    char *p=s; while(*p==' '||*p=='*'||*p=='\t') p++;
    if (p!=s) memmove(s,p,strlen(p)+1);
}

qs_result_t qs_docs_scan_file(qs_arena_t *a, const char *path, qs_doc_vec_t *out) {
    char *text=NULL; qs_size_t tlen=0;
    if (qs_fs_read_file(a,path,&text,&tlen)!=QS_OK) return QS_ERROR_NOT_FOUND;

    char *p=text;
    qs_u64 line=1;

    while (*p) {
        if (*p=='\n') { line++; p++; continue; }
        /* Look for /** QS_DOC */
        if (strncmp(p,"/** QS_DOC",10)==0||strncmp(p,"/*! QS_DOC",10)==0) {
            qs_doc_entry_t e; memset(&e,0,sizeof(e));
            e.source_file=qs_arena_strdup(a,path);
            e.source_line=line;

            /* Scan until closing comment marker */
            char *close=strstr(p,"*/");
            if (!close) break;
            /* Parse lines between open and close */
            char *scan=strchr(p,'\n');
            while (scan&&scan<close) {
                scan++;
                char linebuf[1024];
                char *nl=strchr(scan,'\n');
                qs_size_t ll=nl&&nl<close?(qs_size_t)(nl-scan):(qs_size_t)(close-scan);
                if (ll>=sizeof(linebuf)) ll=sizeof(linebuf)-1;
                memcpy(linebuf,scan,ll); linebuf[ll]='\0';
                trim_leading(linebuf);

                if (strncmp(linebuf,"@brief",6)==0) {
                    char *v=linebuf+6; while(*v==' ') v++;
                    e.brief=qs_arena_strdup(a,v);
                } else if (strncmp(linebuf,"@param",6)==0) {
                    if (e.param_count<16) {
                        char *v=linebuf+6; while(*v==' ') v++;
                        e.params[e.param_count++]=qs_arena_strdup(a,v);
                    }
                } else if (strncmp(linebuf,"@return",7)==0) {
                    char *v=linebuf+7; while(*v==' ') v++;
                    e.returns=qs_arena_strdup(a,v);
                } else if (strncmp(linebuf,"@example",8)==0) {
                    char *v=linebuf+8; while(*v==' ') v++;
                    e.example=qs_arena_strdup(a,v);
                }
                scan=nl;
            }

            /* Extract symbol name from next non-blank line after close */
            char *after=close+2;
            while(*after&&isspace((unsigned char)*after)) after++;
            char *sym_end=after; while(*sym_end&&*sym_end!='\n'&&*sym_end!='{') sym_end++;
            qs_size_t slen=(qs_size_t)(sym_end-after);
            if (slen>0&&slen<256) {
                char tmp[256]; memcpy(tmp,after,slen); tmp[slen]='\0';
                e.symbol_name=qs_arena_strdup(a,tmp);
            }
            qs_doc_vec_push(out,e);
            p=close+2;
            continue;
        }
        p++;
    }
    return QS_OK;
}

/* Emit a Markdown doc file for all entries from one source file */
qs_result_t qs_docs_emit_markdown(qs_arena_t *a, const qs_doc_vec_t *entries,
                                    const char *module_name, const char *out_path) {
    FILE *f=fopen(out_path,"w"); if(!f) return QS_ERROR_IO;
    fprintf(f,"# %s API Reference\n\n",module_name);
    fprintf(f,"> Auto-generated by qs_build — do not edit.\n\n");
    for (qs_size_t i=0;i<entries->len;i++) {
        const qs_doc_entry_t *e=&entries->data[i];
        if (e->symbol_name) fprintf(f,"## `%s`\n\n",e->symbol_name);
        if (e->brief)       fprintf(f,"%s\n\n",e->brief);
        if (e->param_count) {
            fprintf(f,"**Parameters:**\n\n");
            for (qs_size_t j=0;j<e->param_count;j++)
                fprintf(f,"- `%s`\n",e->params[j]);
            fprintf(f,"\n");
        }
        if (e->returns)  fprintf(f,"**Returns:** %s\n\n",e->returns);
        if (e->example)  fprintf(f,"**Example:**\n```\n%s\n```\n\n",e->example);
        fprintf(f,"---\n\n");
    }
    fclose(f);
    return QS_OK;
}

/* Emit a JSON API manifest for Forge:Visuals block registry */
qs_result_t qs_docs_emit_json(qs_arena_t *a, const qs_doc_vec_t *entries,
                                const char *module_name, const char *out_path) {
    FILE *f=fopen(out_path,"w"); if(!f) return QS_ERROR_IO;
    fprintf(f,"{\n  \"module\": \"%s\",\n  \"blocks\": [\n",module_name);
    for (qs_size_t i=0;i<entries->len;i++) {
        const qs_doc_entry_t *e=&entries->data[i];
        fprintf(f,"    {\n");
        fprintf(f,"      \"id\": \"%s_%.*s\",\n",module_name,
            e->symbol_name?(int)strlen(e->symbol_name):0,
            e->symbol_name?e->symbol_name:"");
        fprintf(f,"      \"name\": \"%s\",\n",e->symbol_name?e->symbol_name:"");
        fprintf(f,"      \"brief\": \"%s\",\n",e->brief?e->brief:"");
        fprintf(f,"      \"file\": \"%s\",\n",e->source_file?e->source_file:"");
        fprintf(f,"      \"line\": %llu,\n",(unsigned long long)e->source_line);
        fprintf(f,"      \"params\": [");
        for (qs_size_t j=0;j<e->param_count;j++)
            fprintf(f,"%s\"%s\"",j?",":"",e->params[j]);
        fprintf(f,"]\n    }%s\n",i+1<entries->len?",":"");
    }
    fprintf(f,"  ]\n}\n");
    fclose(f);
    return QS_OK;
}
